package org.kodein.mock.ksp

import com.google.devtools.ksp.containingFile
import com.google.devtools.ksp.getAllSuperTypes
import com.google.devtools.ksp.isAbstract
import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.*
import kotlin.reflect.KClass
import kotlin.reflect.KType


/**
 * KSP [SymbolProcessor] that powers MocKMP code generation.
 *
 * Each processing round ([process]) scans the module for MocKMP annotations and emits three kinds
 * of files, in this order:
 *
 * - **Mocks**: for every interface referenced by `@Mock` or `@UsesMocks(...)`, a `MockXxx` class
 *   implementing it, delegating every member to an injected [org.kodein.mock.Mocker]
 *   (see [Round.generateMockClass]).
 * - **Fakes**: for every type referenced by `@Fake`, `@UsesFakes(...)`, or transitively required
 *   as a non-nullable, non-defaulted constructor parameter of another fake, a top-level
 *   `fakeXxx(): Xxx` function that builds a placeholder instance (see [Round.generateFakeFunction]).
 * - **Injectors**: for every class with `@Mock`/`@Fake` annotated properties, a
 *   `Mocker.injectMocks(receiver: Xxx)` function that sets them all (see [Round.generateInjector]).
 *
 * Once at least one mock or fake exists, three small dispatch functions are additionally emitted
 * into [accessorsPackage] — `Mocker.mock(KClass<T>): T`, `fake(KType): T` and
 * `Mocker.injectMocks(Any)` — matching the `expect` declarations generated by the MocKMP Gradle
 * plugin (see `mockmp-gradle-plugin/src/main/resources/mockmp.multi.kt`).
 *
 * The whole pipeline for a single round is implemented by [Round], instantiated fresh on every
 * [process] call so this processor itself carries no state between rounds.
 */
class MocKMPProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val throwErrors: Boolean,
    public: Boolean,
    private val accessorsPackage: String,
    private val multiplatform: Boolean,
) : SymbolProcessor {

    private companion object {
        val mockerTypeName = ClassName("org.kodein.mock", "Mocker")

        // Fully-qualified names of the annotations MocKMP looks for.
        const val ANNOTATION_MOCK = "org.kodein.mock.Mock"
        const val ANNOTATION_FAKE = "org.kodein.mock.Fake"
        const val ANNOTATION_USES_MOCKS = "org.kodein.mock.UsesMocks"
        const val ANNOTATION_USES_FAKES = "org.kodein.mock.UsesFakes"
        const val ANNOTATION_FAKE_PROVIDER = "org.kodein.mock.FakeProvider"

        /**
         * Types for which a literal placeholder can be emitted directly instead of generating (or
         * looking up) a `fakeXxx()` function. Maps a type's qualified name to a KotlinPoet format
         * string and its single format argument (a literal, or a [MemberName] to a factory function).
         */
        val builtins = mapOf(
            "kotlin.Unit" to ("%L" to "Unit"),
            "kotlin.Boolean" to ("%L" to "false"),
            "kotlin.Byte" to ("%L" to "0"),
            "kotlin.Short" to ("%L" to "0"),
            "kotlin.Int" to ("%L" to "0"),
            "kotlin.Long" to ("%L" to "0L"),
            "kotlin.Float" to ("%L" to "0f"),
            "kotlin.Double" to ("%L" to "0.0"),
            "kotlin.String" to ("%L" to "\"\""),
            "kotlin.collections.List" to ("%M()" to MemberName("kotlin.collections", "emptyList")),
            "kotlin.collections.ArrayList" to ("%M()" to MemberName("kotlin.collections", "ArrayList")),
            "java.util.ArrayList" to ("%M()" to MemberName("kotlin.collections", "ArrayList")),
            "kotlin.collections.ArrayDeque" to ("%M()" to MemberName("kotlin.collections", "ArrayDeque")),
            "kotlin.collections.Set" to ("%M()" to MemberName("kotlin.collections", "emptySet")),
            "kotlin.collections.HashSet" to ("%M()" to MemberName("kotlin.collections", "HashSet")),
            "java.util.HashSet" to ("%M()" to MemberName("kotlin.collections", "HashSet")),
            "kotlin.collections.LinkedHashSet" to ("%M()" to MemberName("kotlin.collections", "LinkedHashSet")),
            "java.util.LinkedHashSet" to ("%M()" to MemberName("kotlin.collections", "LinkedHashSet")),
            "kotlin.collections.Map" to ("%M()" to MemberName("kotlin.collections", "emptyMap")),
            "kotlin.collections.HashMap" to ("%M()" to MemberName("kotlin.collections", "HashMap")),
            "java.util.HashMap" to ("%M()" to MemberName("kotlin.collections", "HashMap")),
            "kotlin.collections.LinkedHashMap" to ("%M()" to MemberName("kotlin.collections", "LinkedHashMap")),
            "java.util.LinkedHashMap" to ("%M()" to MemberName("kotlin.collections", "LinkedHashMap")),
            "kotlin.Array" to ("%M()" to MemberName("kotlin", "emptyArray"))
        )
    }

    private val KSType.isAnyFunctionType get() = isFunctionType || isSuspendFunctionType

    /** Follows `typealias` chains to the underlying declaration. */
    private fun KSType.aliasedDeclaration(): KSDeclaration {
        var decl = declaration
        while (decl is KSTypeAlias) decl = decl.type.resolve().declaration
        return decl
    }

    private val visibilityModifier = if (public) KModifier.PUBLIC else KModifier.INTERNAL

    /** Thrown to abort processing of the current round with a location-tagged message. */
    private class Error(message: String, val node: KSNode) : Exception(message)

    override fun process(resolver: Resolver): List<KSAnnotated> =
        try {
            Round(resolver).run()
        } catch (e: Error) {
            logger.error("MocKMP: ${e.message}", e.node)
            if (throwErrors) throw e
            emptyList()
        }

    // region Error reporting

    /** Renders [this] node as a human-readable path, for messages when no [FileLocation] is available. */
    private fun KSNode.asString(): String = when (this) {
        is KSValueParameter -> {
            val nameStr = name?.asString() ?: "?"
            if (parent != null) "${parent!!.asString()}($nameStr)"
            else nameStr
        }
        is KSClassDeclaration -> this.qualifiedName?.asString() ?: this.simpleName.asString()
        else -> (parent?.let { it.asString() + "." } ?: "") + toString()
    }

    /** Fails the current round with [message], pointing [logger] at [node]'s source location when known. */
    private fun error(node: KSNode, message: String): Nothing {
        val prefix = when (val loc = node.location) {
            is FileLocation -> "$node (${loc.filePath}:${loc.lineNumber})"
            is NonExistLocation -> node.asString()
        }
        throw Error("$prefix: $message", node)
    }

    // endregion

    /** The files and annotation sites that referenced a to-be-generated mock or fake, accumulated across annotations. */
    private class ToProcess {
        val files = HashSet<KSFile>()
        val references = HashSet<KSNode>()

        /**
         * True when this entry was discovered implicitly — as a type reachable from a mocked
         * interface's signatures (see [Round.seedImplicitPlaceholders]), not requested directly via
         * `@Mock`/`@Fake`/`@UsesMocks`/`@UsesFakes`. Implicit entries that turn out to be
         * unconstructible get a generated function that throws at runtime instead of aborting the
         * KSP round — nobody asked for that type directly, so failing the whole build over it would
         * be disproportionate. Explicit entries keep failing fast at compile time.
         */
        var implicit: Boolean = false
    }

    // region Naming

    /** The `Outer_Inner_` prefix identifying [this] declaration's chain of enclosing declarations, if any. */
    private fun KSDeclaration.parentPrefix(): String = buildString {
        var pDecl = parentDeclaration
        while (pDecl != null) {
            append(pDecl.simpleName.asString())
            append("_")
            pDecl = pDecl.parentDeclaration
        }
    }

    /** The `foo_bar_` prefix identifying [this] declaration's package, empty for the root package. */
    private fun KSDeclaration.packagePrefix(): String =
        packageName.asString().replace('.', '_').withNonEmptySuffix("_")

    /**
     * A name-safe identifier for the `fakeXxx()` function generated for [this] type: unique per
     * package (`fakedata_Data` vs. `fakefoo_Data`, since both live in the same generated
     * `fakes.kt`), distinct type argument list (`fakeGenDataXkotlin_IntX`, `fakeGenDataXkotlin_StringX`,
     * ...), nesting (`fakeFakeTests_FakeAny` for a nested class `FakeAny` inside `FakeTests`) and
     * nullability.
     */
    private fun KSType.toFunName(): String {
        val prefix = declaration.packagePrefix() + (if (isMarkedNullable) "Nul" else "") + declaration.parentPrefix()
        return prefix +
                if (arguments.isEmpty()) declaration.simpleName.asString()
                else "${declaration.simpleName.asString()}X${
                    arguments.joinToString("_") {
                        if (it.variance == Variance.STAR) "STAR"
                        else it.type!!.resolve().toFunName()
                    }
                }X"
    }

    /** The `MockXxx` class name generated for [this] mocked interface. */
    private fun KSDeclaration.toMockName(): String = "Mock" + parentPrefix() + simpleName.asString()

    /**
     * The package a generated `fakeXxx()` function for [this] declaration is emitted into: its own
     * package, except for Kotlin stdlib packages (which this module cannot write into), redirected
     * under a local `fake.` prefix.
     */
    private fun KSDeclaration.fakePackageName(): String =
        if (packageName.isKotlinStdlib()) "fake." + packageName.asString() else packageName.asString()

    // endregion

    /**
     * Mutable state and generation logic of a single KSP processing round. A fresh instance is
     * created per [process] call, so [MocKMPProcessor] itself carries no state across rounds.
     */
    private inner class Round(private val resolver: Resolver) {

        /** Interfaces referenced by `@Mock`/`@UsesMocks`, with the files/nodes that referenced them. */
        private val toMock = HashMap<KSClassDeclaration, ToProcess>()

        /** Generated `MockXxx` class name, per mocked interface — consumed by [generateMockAccessor]. */
        private val mocks = HashMap<KSClassDeclaration, ClassName>()

        /** Types referenced by `@Fake`/`@UsesFakes`, or required transitively (see [expandTransitiveFakes]). */
        private val toFake = HashMap<KSType, ToProcess>()

        /** Generated `fakeXxx()` function name, per faked type — consumed by [generateFakeAccessor]. */
        private val fakes = HashMap<KSType, MemberName>()

        /** User-supplied `@FakeProvider` functions, keyed by the type they provide a fake for. */
        private val providedFakes = HashMap<KSType, KSFunctionDeclaration>()

        /** Properties annotated `@Mock`/`@Fake`, grouped by enclosing class — consumed by [generateInjector]. */
        private val toInject = HashMap<KSClassDeclaration, ArrayList<Pair<String, KSPropertyDeclaration>>>()

        /**
         * Concrete `Array<T>` types (a known component type) needing a placeholder — kept separate
         * from [toFake]/[toMock] because, unlike ordinary generics, `Array<T>::class` is *not*
         * erased on the JVM: each component type is a genuinely distinct runtime class, so
         * `Array<String>::class` and `Array<Int>::class` can't share one `when` branch the way
         * `List<String>::class == List<Int>::class` can. Consumed by [generatePlaceholderAccessor].
         */
        private val placeholderArrayTypes = LinkedHashSet<KSType>()

        /**
         * Function-typed shapes found while seeding implicit placeholders, keyed by the exact
         * declaration KSP resolves the type to (`kotlin.Function1`, `kotlin.coroutines.SuspendFunction1`,
         * etc. — deliberately *not* hand-built from an arity count: the JVM backend's CPS transform
         * means a suspend type's *reified* runtime class doesn't necessarily follow the naming
         * scheme its own frontend declaration suggests, so reusing KSP's own resolution is the only
         * reliable way to get a matching `T::class`). Mapped to (isSuspend, parameterCount), needed
         * to build the placeholder lambda's shape. Kept separate from [toMock] — a generated class
         * can't `: Function1<P1, R>` on Kotlin/JS ("Implementing a function interface is prohibited
         * in JavaScript"), so a plain lambda is used instead — consumed by [generatePlaceholderAccessor].
         */
        private val placeholderFunctionShapes = LinkedHashMap<KSClassDeclaration, Pair<Boolean, Int>>()

        /** Runs the full pipeline for this round: collect, expand, then generate every kind of file. */
        fun run(): List<KSAnnotated> {
            collectAnnotatedSymbols()
            collectFakeProviders()
            seedImplicitPlaceholders()
            expandTransitiveFakes()

            toMock.forEach { (vItf, process) -> generateMockClass(vItf, process) }
            toFake.forEach { (vType, process) -> generateFakeFunction(vType, process) }
            toInject.forEach { (vCls, _) -> generateInjector(vCls) }

            if (mocks.isNotEmpty() || fakes.isNotEmpty()) {
                generateMockAccessor()
                generateFakeAccessor()
                generateInjectorAccessor()
                generatePlaceholderAccessor()
            }

            return emptyList()
        }

        // region Phase 1: collect annotated symbols

        /**
         * Registers [type] as needing a `MockXxx` class, or fails if it isn't an interface or an
         * abstract class. [implicit] marks entries discovered by [seedImplicitPlaceholders] rather
         * than requested directly.
         */
        private fun addMock(type: KSType, files: Iterable<KSFile>, node: KSNode, implicit: Boolean = false) {
            if (type.isFunctionType) return
            val decl = type.declaration
            val isMockable = decl is KSClassDeclaration &&
                    (decl.classKind == ClassKind.INTERFACE || (decl.classKind == ClassKind.CLASS && Modifier.ABSTRACT in decl.modifiers))
            if (!isMockable) error(node, "Cannot generate mock for non interface $decl")
            toMock.getOrPut(decl) { ToProcess().apply { this.implicit = implicit } }.let {
                it.files.addAll(files)
                it.references.add(node)
            }
        }

        /**
         * Registers [type] as needing a `fakeXxx()` function, or fails if it isn't a fakeable
         * class/enum. Sealed classes/interfaces are allowed through — [generateFakeFunction]
         * resolves them to a constructible permitted subclass at generation time. [implicit] marks
         * entries discovered by [seedImplicitPlaceholders] rather than requested directly.
         */
        private fun addFake(type: KSType, files: Iterable<KSFile>, node: KSNode, implicit: Boolean = false) {
            val decl = type.declaration

            if (decl !is KSClassDeclaration) {
                error(node, "Cannot generate fake for ${decl.javaClass.simpleName} ${decl.qualifiedName?.asString() ?: decl.simpleName.asString()}")
            }
            val isSealed = Modifier.SEALED in decl.modifiers
            if (!isSealed && (decl.isAbstract() || decl.classKind !in arrayOf(ClassKind.CLASS, ClassKind.ENUM_CLASS))) {
                error(node, "Cannot generate fake for ${if (decl.isAbstract()) "abstract " else ""}${decl.classKind.type} ${decl.qualifiedName?.asString() ?: decl.simpleName.asString()}")
            }
            toFake.getOrPut(type) { ToProcess().apply { this.implicit = implicit } }.let {
                it.files.addAll(files)
                it.references.add(node)
            }
        }

        /** Finds every property annotated [annotationName] (or its setter), registers its class for injection, and [add]s its type. */
        private fun lookUpFields(annotationName: String, add: (KSType, Iterable<KSFile>, KSNode) -> Unit) {
            val symbols = resolver.getSymbolsWithAnnotation(annotationName)
            symbols.forEach { symbol ->
                val prop = when (symbol) {
                    is KSPropertySetter -> symbol.receiver
                    is KSPropertyDeclaration -> {
                        if (!symbol.isMutable) error(symbol, "$symbol is immutable but is annotated with @${annotationName.split(".").last()}")
                        symbol
                    }
                    else -> error(symbol, "$symbol is not a property nor a property setter but is annotated with @${annotationName.split(".").last()} (is ${symbol::class.simpleName})")
                }
                val cls = prop.parentDeclaration as? KSClassDeclaration ?: error(symbol, "Cannot generate injector for $prop as it is not inside a class")
                toInject.getOrPut(cls) { ArrayList() }.add(annotationName to prop)
                add(prop.type.resolve(), listOf(cls.containingFile!!), symbol)
            }
        }

        /** Finds every declaration annotated `@UsesMocks(...)`/`@UsesFakes(...)` and [add]s each type listed in [annotationName]'s array argument. */
        private fun lookUpUses(annotationName: String, add: (KSType, Iterable<KSFile>, KSNode) -> Unit) {
            val uses = resolver.getSymbolsWithAnnotation(annotationName)
            uses.forEach { use ->
                val anno = use.annotations.first { it.annotationType.resolve().declaration.qualifiedName!!.asString() == annotationName }
                (anno.arguments.first().value as List<*>).forEach {
                    add((it as KSType), listOf(use.containingFile!!), use)
                }
            }
        }

        /** Populates [toMock], [toFake] and [toInject] from `@Mock`, `@Fake`, `@UsesMocks` and `@UsesFakes`. */
        private fun collectAnnotatedSymbols() {
            lookUpFields(ANNOTATION_MOCK, ::addMock)
            lookUpFields(ANNOTATION_FAKE, ::addFake)
            lookUpUses(ANNOTATION_USES_MOCKS, ::addMock)
            lookUpUses(ANNOTATION_USES_FAKES, ::addFake)
        }

        /**
         * Populates [providedFakes] from `@FakeProvider` top-level functions, and removes their
         * return type from [toFake] — a user-supplied provider makes generation unnecessary.
         */
        private fun collectFakeProviders() {
            resolver.getSymbolsWithAnnotation(ANNOTATION_FAKE_PROVIDER).forEach {
                if (it !is KSFunctionDeclaration || it.parent !is KSFile) error(it, "Only top-level functions can be annotated with @FakeProvider")
                val type = it.returnType!!.resolve()
                val typeDeclaration = type.declaration
                if (typeDeclaration !is KSClassDeclaration) error(it, "@FakeProvider functions must return class types.")
                if (type in providedFakes) error(it, "Only one @FakeProvider function must exist for this type (other is ${providedFakes[type]!!.asString()}).")
                toFake.remove(type)
                providedFakes[type] = it
            }
        }

        // endregion

        // region Phase 1.5: implicit placeholders

        /**
         * A representative [KSType] for [this] declaration, substituting each type parameter with
         * its first bound (e.g. `T : Any` becomes `Any`) — the same "good enough" stand-in
         * [generateMockAccessor] already uses when the concrete type argument is unknown.
         */
        private fun KSClassDeclaration.asBoundedType(): KSType =
            asType(typeParameters.map { resolver.getTypeArgument(it.bounds.first(), Variance.INVARIANT) })

        /** The stand-in type for [this] type parameter when no argument is known: its first bound, or `Any?`. */
        private fun KSTypeParameter.boundType(): KSType =
            bounds.firstOrNull()?.resolve() ?: resolver.builtIns.anyType.makeNullable()

        /**
         * If [decl] is sealed (class or interface), returns its first permitted subclass, resolved
         * recursively through nested sealed hierarchies. Returns [decl] unchanged when it isn't
         * sealed, or when a sealed hierarchy has no permitted subclasses (construction then fails
         * naturally later, with a reasonable "no public constructor" message).
         *
         * [resolveSealedTargetType] is the type-level counterpart, and must keep picking the same
         * subclass as this one.
         */
        private fun resolveSealedTarget(decl: KSClassDeclaration): KSClassDeclaration {
            if (Modifier.SEALED !in decl.modifiers) return decl
            val first = decl.getSealedSubclasses().firstOrNull() ?: return decl
            return resolveSealedTarget(first)
        }

        /**
         * Binds the type parameters [declared] is written in terms of to the matching arguments of
         * [actual], recursively — unifying `Swapped<Y, X>` against `Swapped<String, Int>` binds
         * `Y` to `String` and `X` to `Int`.
         */
        private fun bindTypeParameters(declared: KSType, actual: KSType, into: MutableMap<KSTypeParameter, KSType>) {
            val decl = declared.declaration
            if (decl is KSTypeParameter) {
                into[decl] = actual
                return
            }
            declared.arguments.forEachIndexed { index, argument ->
                val declaredArgument = argument.type?.resolve() ?: return@forEachIndexed
                val actualArgument = actual.arguments.getOrNull(index)?.type?.resolve() ?: return@forEachIndexed
                bindTypeParameters(declaredArgument, actualArgument, into)
            }
        }

        /**
         * [resolveSealedTarget] at the type level: the permitted subclass that will actually be
         * constructed for [vType], expressed with *its own* type arguments.
         *
         * A subclass does not have to declare the same type parameters, in the same order, as the
         * sealed parent it extends — `class Impl<X, Y> : Swapped<Y, X>()` is legal — so the parent's
         * arguments cannot simply be indexed by the subclass's parameter positions. They are mapped
         * through the supertype reference the subclass declares ([bindTypeParameters]); a parameter
         * the parent says nothing about falls back to its bound.
         */
        private fun resolveSealedTargetType(vType: KSType): KSType {
            val decl = vType.declaration as? KSClassDeclaration ?: return vType
            if (Modifier.SEALED !in decl.modifiers) return vType
            val sub = decl.getSealedSubclasses().firstOrNull() ?: return vType

            val bindings = HashMap<KSTypeParameter, KSType>()
            sub.superTypes
                .map { it.resolve() }
                .firstOrNull { it.declaration == decl }
                ?.let { bindTypeParameters(it, vType, bindings) }
            val arguments = sub.typeParameters.map { vParam ->
                resolver.getTypeArgument(
                    resolver.createKSTypeReferenceFromKSType(bindings[vParam] ?: vParam.boundType()),
                    Variance.INVARIANT,
                )
            }
            return resolveSealedTargetType(sub.asType(arguments))
        }

        /** Follows type alias declarations (e.g. `typealias BarCB = (String) -> Int`) down to the real type they expand to. */
        private fun KSType.unwrapAliases(): KSType {
            var t = this
            while (t.declaration is KSTypeAlias) t = (t.declaration as KSTypeAlias).type.resolve()
            return t
        }

        /**
         * Registers one type reachable from a mocked interface's signatures as needing a
         * placeholder, unless it's already covered: [builtins], an existing [toMock] entry, or an
         * existing [toFake] entry. Nullable types need no placeholder (`null` is a valid one). An
         * unresolved type parameter is substituted with its first bound, same as [asBoundedType].
         *
         * The dispatch *key* is always the original type — the one `isAny<T>()`/etc. will actually
         * ask for at runtime (e.g. `SItf::class`, not `SItf.C::class`) — even when [resolveSealedTarget]
         * means the *generated body* ends up constructing a different, concrete permitted subclass;
         * [generateFakeFunction] already does this same redirection internally.
         *
         * `kotlin.Array<T>` gets dedicated handling in [placeholderArrayTypes]: unlike ordinary
         * generics, it isn't erased on the JVM, so a single shared `Array::class` branch can't work
         * for every component type.
         *
         * Function types get dedicated handling in [placeholderFunctionShapes] too — not because
         * `T::class` is any different for them (it erases to `kotlin.Function1`/etc. exactly like
         * any other interface), but because *constructing* a value is: Kotlin/JS forbids a class
         * declaring `: Function1<P1, R>` as a supertype ("Implementing a function interface is
         * prohibited in JavaScript"), so the placeholder for a function-typed target has to be a
         * plain lambda rather than a `MockXxx` class.
         */
        private fun registerFunctionShape(resolved: KSType) {
            val decl = resolved.declaration as? KSClassDeclaration ?: return
            placeholderFunctionShapes[decl] = resolved.isSuspendFunctionType to (resolved.arguments.size - 1)
        }

        private fun seedImplicitPlaceholder(type: KSType) {
            if (type.nullability != Nullability.NOT_NULL) return
            var resolved = type.unwrapAliases()
            if (resolved.isAnyFunctionType) {
                registerFunctionShape(resolved)
                return
            }
            if (resolved.declaration is KSTypeParameter) {
                resolved = (resolved.declaration as KSTypeParameter).bounds.first().resolve().unwrapAliases()
                if (resolved.isAnyFunctionType) {
                    registerFunctionShape(resolved)
                    return
                }
            }
            val decl = resolved.declaration
            if (decl !is KSClassDeclaration) return
            if (decl.qualifiedName?.asString() == "kotlin.Array") {
                placeholderArrayTypes += resolved
                return
            }
            if (decl.qualifiedName?.asString() in builtins) return
            if (decl in toMock || resolved in toFake) return
            val target = resolveSealedTarget(decl)
            when {
                target != decl -> toFake[resolved] = ToProcess().apply { implicit = true }
                decl.classKind == ClassKind.INTERFACE || (decl.classKind == ClassKind.CLASS && Modifier.ABSTRACT in decl.modifiers) ->
                    toMock[decl] = ToProcess().apply { implicit = true }
                decl.classKind == ClassKind.CLASS || decl.classKind == ClassKind.ENUM_CLASS ->
                    toFake[resolved] = ToProcess().apply { implicit = true }
                else -> {}
            }
        }

        /**
         * Walks every interface/abstract class already in [toMock] and seeds a placeholder for
         * every parameter, return, and property type reachable from its members — the set of types
         * `isAny()`/`isEqual()`/etc. may need to return a value for. For an *implicit* entry, only
         * abstract members are walked, mirroring [generateMockClass]'s decision to only override
         * abstract members for such a target — walking (and then generating an override for) a JDK
         * default method like `Iterable.forEach(Consumer)` has repeatedly proven to be a source of
         * variance conflicts and out-of-bounds package restrictions for no benefit, since a
         * placeholder is never meant to be genuinely invoked anyway. Runs as a worklist since a
         * newly-seeded abstract class or interface may itself reference further types.
         */
        private fun seedImplicitPlaceholders() {
            val toExplore = ArrayDeque(toMock.keys)
            while (toExplore.isNotEmpty()) {
                val vItf = toExplore.removeFirst()
                val overrideAll = vItf.classKind == ClassKind.INTERFACE && !toMock.getValue(vItf).implicit
                val before = HashSet(toMock.keys)
                vItf.getAllProperties()
                    .filter { it.isAbstract() }
                    .forEach { vProp -> seedImplicitPlaceholder(vProp.type.resolve()) }
                vItf.getAllFunctions()
                    .filter { if (overrideAll) it.simpleName.asString() !in listOf("equals", "hashCode") else it.isAbstract }
                    .forEach { vFun ->
                        vFun.parameters.forEach { seedImplicitPlaceholder(it.type.resolve()) }
                        vFun.returnType?.let { seedImplicitPlaceholder(it.resolve()) }
                    }
                toMock.keys.forEach { if (it !in before) toExplore.add(it) }
            }
        }

        // endregion

        // region Phase 2: transitive fakes

        /**
         * [type] with every reference to one of [vCls]'s type parameters replaced by the matching
         * type argument of [vType] — `GenData<T>` becomes `GenData<String>` when [vType] is
         * `Wrap<String>` — or `null` when one of them belongs to an enclosing declaration rather
         * than to [vCls], which the arguments of [vType] say nothing about.
         *
         * When [vType] projects a type parameter with a star — which is all a `KClass` reference can
         * express, so it is what every `@UsesFakes(Generic::class)` produces — the parameter's first
         * bound stands in for it, the same "good enough" substitute [asBoundedType] uses. An
         * undeclared bound is `Any?`, which is why `NullGenData<T>(val content: T)` fakes its content
         * as `null` while `NonNullGenData<T : Any>` fakes it as an `Any` instance.
         *
         * Substitution is recursive: a type parameter can be nested at any depth (`GenData<GenData<T>>`,
         * `() -> GenData<T>`), and only substituting a *bare* type parameter would leave the rest
         * unresolved — with no `fakeGenDataXTX()` function to call for it.
         *
         * Returns [type] itself when nothing was substituted: [toFake], [fakes] and [providedFakes]
         * are keyed by [KSType], so a rebuilt-but-equivalent instance must never be introduced needlessly.
         */
        private fun substituteTypeParameters(type: KSType, vCls: KSClassDeclaration, vType: KSType): KSType? {
            val decl = type.declaration
            if (decl is KSTypeParameter) {
                val index = vCls.typeParameters.indexOf(decl)
                if (index < 0) return null
                val resolved = vType.arguments.getOrNull(index)?.type?.resolve() ?: decl.boundType()
                // `T?` substitutes to `String?`, not to `String`: dropping the nullability would make
                // constructorParamTypeToFake (which skips nullable parameters) and resolveConstructorArgs
                // (which emits `null` for them) disagree on whether a fake is needed at all.
                return if (type.isMarkedNullable) resolved.makeNullable() else resolved
            }
            if (type.arguments.isEmpty()) return type

            var substituted = false
            val arguments = type.arguments.map { argument ->
                val argumentType = argument.type?.resolve() ?: return@map argument // A star projection has nothing to substitute.
                val resolved = substituteTypeParameters(argumentType, vCls, vType) ?: return null
                if (resolved == argumentType) return@map argument
                substituted = true
                resolver.getTypeArgument(resolver.createKSTypeReferenceFromKSType(resolved), argument.variance)
            }
            return if (substituted) type.replace(arguments) else type
        }

        /**
         * Resolves the type a fake is needed for, for constructor [param] of fake class [vCls]
         * (whose fake is being generated for [vType]) — or `null` if [param] needs no fake: it has
         * a default value, is nullable, resolves to a [builtins] type, or already has one
         * ([providedFakes] or [toFake]).
         */
        private fun constructorParamTypeToFake(vCls: KSClassDeclaration, vType: KSType, param: KSValueParameter, process: ToProcess): KSType? {
            if (param.hasDefault) return null
            // Nullability is tested *after* substitution, as [resolveConstructorArgs] does: a type
            // parameter can substitute to a nullable type, and the two must agree on which
            // parameters get a fake and which are simply set to `null`.
            var paramType = substituteTypeParameters(param.type.resolve(), vCls, vType)
                ?: error(param, "Could not resolve generic parameter $param (${process.references.firstOrNull()?.location})")
            if (paramType.nullability != Nullability.NOT_NULL) return null

            if (paramType.isAnyFunctionType) {
                paramType = paramType.arguments.last().type!!.resolve()
            }
            return paramType.takeIf { it.aliasedDeclaration().qualifiedName?.asString() !in builtins && it !in providedFakes && it !in toFake }
        }

        /**
         * Breadth-first expansion of [toFake]: a fake class may itself require fakes for its own
         * constructor parameter types (a `data class Foo(val bar: Bar)` needs `fakeBar()` too), so
         * this walks the constructor graph and adds any parameter type not already covered. Also
         * seeds from [toMock]'s abstract-class entries (see [addMock]) — their superclass
         * constructor call (built by [addSuperclassConstructorArgs]) needs the same treatment.
         * Discovered types inherit their parent's [ToProcess.implicit] flag: if the whole chain
         * exists only because of an implicit placeholder need, nobody asked for any of it directly,
         * so none of it should be able to abort the KSP round.
         */
        private fun expandTransitiveFakes() {
            val abstractMockSeeds = toMock.entries
                .filter { (decl, _) -> Modifier.ABSTRACT in decl.modifiers }
                .map { (decl, process) -> decl.asBoundedType() to process }
            val toExplore = ArrayDeque(toFake.map { it.toPair() } + abstractMockSeeds)
            while (toExplore.isNotEmpty()) {
                val (type, process) = toExplore.removeFirst()
                // The constructor that will be called is the sealed target's, not the sealed parent's
                // (which isn't even public) — the two phases must walk the same one.
                val targetType = resolveSealedTargetType(type)
                val cls = targetType.declaration as KSClassDeclaration
                cls.firstPublicConstructor()?.parameters?.forEach { param ->
                    val paramTypeToFake = constructorParamTypeToFake(cls, targetType, param, process) ?: return@forEach
                    addFake(paramTypeToFake, process.files, param, implicit = process.implicit)
                    toExplore.add(paramTypeToFake to process)
                }
            }
        }

        // endregion

        // region Phase 3: mock generation

        /**
         * Appends `: SuperClass(arg1, arg2, ...)` superclass constructor arguments to [gCls] for
         * abstract class [vCls]'s primary constructor, resolved the same way fake-class constructor
         * arguments are (see [resolveConstructorArgs]) — the placeholder instance still has to
         * satisfy its supertype's real constructor.
         */
        private fun addSuperclassConstructorArgs(gCls: TypeSpec.Builder, vCls: KSClassDeclaration, filesDeps: MutableSet<KSFile>) {
            val vCstr = vCls.firstPublicConstructor() ?: return
            resolveConstructorArgs(vCls, vCstr, vCls.asBoundedType(), filesDeps).forEach { (format, values) ->
                gCls.addSuperclassConstructorParameter(format, *values.toTypedArray())
            }
        }

        /**
         * Builds the `MockXxx` class shell for [vItf]: supertype (interface or abstract class),
         * type variables, and the private `mocker` constructor property. Its `init` block registers
         * [providePlaceholder] on that `mocker` — this is what makes the placeholder provider
         * reliably available by the time any `isAny()`/`isEqual()`/etc. call could need it, since
         * you cannot obtain a mock instance without going through this constructor first.
         */
        private fun mockClassBuilder(vItf: KSClassDeclaration, mockClassName: String, filesDeps: MutableSet<KSFile>): Pair<TypeSpec.Builder, PropertySpec> {
            val gCls = TypeSpec.classBuilder(mockClassName)
                .addModifiers(visibilityModifier)
            val superType =
                if (vItf.typeParameters.isEmpty()) vItf.toClassName()
                else vItf.toClassName().parameterizedBy(vItf.typeParameters.map { it.toTypeVariableName() })
            if (vItf.classKind == ClassKind.INTERFACE) {
                gCls.addSuperinterface(superType)
            } else {
                gCls.superclass(superType)
                addSuperclassConstructorArgs(gCls, vItf, filesDeps)
            }
            vItf.typeParameters.forEach { vParam -> gCls.addTypeVariable(vParam.toTypeVariableName()) }
            gCls.primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("mocker", mockerTypeName)
                    .build()
            )
            val mocker = PropertySpec.builder("mocker", mockerTypeName)
                .initializer("mocker")
                .addModifiers(KModifier.PRIVATE)
                .build()
            gCls.addProperty(mocker)
            gCls.addInitializerBlock(
                CodeBlock.of("mocker.registerPlaceholderProvider(::%M)\n", MemberName(accessorsPackage, "providePlaceholder"))
            )
            return gCls to mocker
        }

        /**
         * The [org.kodein.mock.Mocker]-backed override for one abstract property of the mocked
         * interface, e.g. for `val bar: String` and mutable `var baz: Int`:
         *
         * ```
         * override val bar: String get() = this.mocker.register(this, "get:bar")
         * override var baz: Int
         *     get() = this.mocker.register(this, "get:baz")
         *     set(value) { this.mocker.register(this, "set:baz", value) }
         * ```
         */
        private fun mockedProperty(vProp: KSPropertyDeclaration, vItf: KSClassDeclaration, mocker: PropertySpec): PropertySpec {
            val typeParamResolver = vProp.typeParameters.toTypeParameterResolver(vItf.typeParameters.toTypeParameterResolver())
            val gPropType = vProp.type.toTypeName(typeParamResolver)
            val gProp = PropertySpec.builder(vProp.simpleName.asString(), gPropType)
                .addModifiers(KModifier.OVERRIDE)
                .getter(
                    FunSpec.getterBuilder()
                        .addStatement("return this.%N.register(this, %S)", mocker, "get:${vProp.simpleName.asString()}")
                        .build()
                )
            vProp.annotations.forEach { gProp.addAnnotation(it.toAnnotationSpec()) }
            if (vProp.isMutable) {
                gProp.mutable(true)
                    .setter(
                        FunSpec.setterBuilder()
                            .addParameter("value", gPropType)
                            .addStatement("return this.%N.register(this, %S, value)", mocker, "set:${vProp.simpleName.asString()}")
                            .build()
                    )
            }
            return gProp.build()
        }

        /**
         * The `"name(kotlin.Int, vararg kotlin.String)"` key computed for [vFun] — the same key
         * [org.kodein.mock.Mocker.register]/`registerSuspend` receive as `method`, and that
         * `every { }` blocks match recorded calls against.
         */
        private fun registrationKey(vFun: KSFunctionDeclaration): String {
            val paramsDescription = vFun.parameters.joinToString {
                (it.type.resolve().declaration as? KSClassDeclaration)?.qualifiedName?.asString()?.let { str ->
                    if (it.isVararg) "vararg $str" else str
                } ?: "?"
            }
            return "${vFun.simpleName.asString()}($paramsDescription)"
        }

        /**
         * The [org.kodein.mock.Mocker]-backed override for one function of the mocked interface,
         * e.g. for `fun baz(i: Int): String`:
         *
         * ```
         * override fun baz(i: Int): String = this.mocker.register(this, "baz(kotlin.Int)", i)
         * ```
         *
         * Non-abstract (default) interface members get a `default = { super.baz(i) }` fallback, so
         * that mocking them with `every { }` remains optional.
         */
        private fun mockedFunction(vFun: KSFunctionDeclaration, vItf: KSClassDeclaration, mocker: PropertySpec): FunSpec {
            val gFun = FunSpec.builder(vFun.simpleName.asString())
                .addModifiers(KModifier.OVERRIDE)
            val typeParamResolver = vFun.typeParameters.toTypeParameterResolver(vItf.typeParameters.toTypeParameterResolver())
            vFun.typeParameters.forEach { vParam -> gFun.addTypeVariable(vParam.toTypeVariableName(typeParamResolver)) }
            gFun.addModifiers((vFun.modifiers - Modifier.ABSTRACT - Modifier.OPEN - Modifier.OPERATOR).mapNotNull { it.toKModifier() })
            gFun.returns(vFun.returnType!!.toTypeName(typeParamResolver))
            vFun.annotations.forEach { gFun.addAnnotation(it.toAnnotationSpec()) }
            vFun.parameters.forEach { vParam ->
                gFun.addParameter(vParam.name!!.asString(), vParam.type.toTypeName(typeParamResolver), if (vParam.isVararg) listOf(KModifier.VARARG) else emptyList())
            }
            val paramsCall = if (vFun.parameters.isEmpty()) "" else vFun.parameters.joinToString { it.name!!.asString() }
            val register = if (Modifier.SUSPEND in vFun.modifiers) "registerSuspend" else "register"
            val default = if (vFun.isAbstract) "" else "default = { super.${vFun.simpleName.asString()}($paramsCall) }"
            gFun.addStatement(
                "return this.%N.$register(this, %S${paramsCall.withNonEmptyPrefix(", ")}${default.withNonEmptyPrefix(", ")})",
                mocker,
                registrationKey(vFun)
            )
            return gFun.build()
        }

        /**
         * Generates the `MockXxx` class implementing interface (or, for a placeholder-only target,
         * overriding abstract class) [vItf], into its own file, e.g. for
         * `interface Foo { val bar: String; fun baz(i: Int): String }`:
         *
         * ```
         * internal class MockFoo(mocker: Mocker) : Foo {
         *     private val mocker: Mocker = mocker
         *     override val bar: String get() = this.mocker.register(this, "get:bar")
         *     override fun baz(i: Int): String = this.mocker.register(this, "baz(kotlin.Int)", i)
         * }
         * ```
         *
         * For an *explicitly* requested interface, every member is overridden — abstract members
         * through the mocker, non-abstract (default) ones with a `default = { super.foo() }`
         * fallback so mocking them remains optional. For an abstract class, or an *implicitly*
         * discovered interface (see [ToProcess.implicit]), only the abstract members are overridden:
         * a placeholder is never meant to be genuinely invoked, so there's no need to touch concrete
         * members (which may be `final`, or — as JDK interop default methods like
         * `Iterable.forEach(Consumer)` have shown — carry variance that only conflicts when
         * re-declared as an explicit override).
         *
         * Generated into [KSDeclaration.fakePackageName] rather than [vItf]'s own package: besides
         * the same stdlib-write restriction fakes already redirect around, some interfaces
         * (`kotlin.Function1` and friends) live directly in the bare `kotlin` package, which only the
         * standard library itself is allowed to contribute to.
         *
         * Records the generated class name into [mocks], consumed by [generateMockAccessor].
         */
        private fun generateMockClass(vItf: KSClassDeclaration, process: ToProcess) {
            val mockClassName = vItf.toMockName()
            val mockPkg = vItf.fakePackageName()
            val gFile = FileSpec.builder(mockPkg, mockClassName)
            val filesDeps = HashSet(process.files)
            val (gCls, mocker) = mockClassBuilder(vItf, mockClassName, filesDeps)
            val overrideAll = vItf.classKind == ClassKind.INTERFACE && !process.implicit

            vItf.getAllProperties()
                .filter { it.isAbstract() }
                .forEach { vProp -> gCls.addProperty(mockedProperty(vProp, vItf, mocker)) }

            vItf.getAllFunctions()
                .filter { if (overrideAll) it.simpleName.asString() !in listOf("equals", "hashCode") else it.isAbstract }
                .forEach { vFun -> gCls.addFunction(mockedFunction(vFun, vItf, mocker)) }

            gFile.addType(gCls.build().also { mocks[vItf] = ClassName(mockPkg, it.name!!) })
            gFile.build().writeTo(codeGenerator, Dependencies(true, *filesDeps.toTypedArray()))
        }

        // endregion

        // region Phase 4: fake generation

        /**
         * Resolves how to initialize a value of [type], as a KotlinPoet `(format, arg)` pair
         * suitable for `addStatement("... $template ...", ..., value)`:
         *  1. a [builtins] literal or factory call, if [type] (after unwrapping any type alias) is one;
         *  2. a call to the user's `@FakeProvider` function, if one was registered for [type];
         *  3. otherwise, a call to the generated `fakeXxx()` function for [type].
         *
         * Any file backing a case-2 provider is added to [filesDeps] so the generated file
         * correctly depends on it.
         *
         * NOTE: this unifies what used to be two separately-inlined copies of this resolution (one
         * for constructor parameters, one for `@Fake` properties). The property-injection call site
         * ([addFakeInjection]) did not previously unwrap type aliases nor redirect stdlib packages
         * through [fakePackageName] — both are applied uniformly now; the difference is unreachable
         * for any type already covered by [builtins], which is the only stdlib case exercised today.
         */
        private fun fakeInitializerOf(type: KSType, filesDeps: MutableSet<KSFile>): Pair<String, Any> {
            val decl = type.aliasedDeclaration()
            val builtIn = builtins[decl.qualifiedName!!.asString()]
            return when {
                builtIn != null -> builtIn
                type in providedFakes -> {
                    val f = providedFakes[type]!!
                    f.containingFile?.let { filesDeps += it }
                    "%M()" to MemberName(f.packageName.asString(), f.simpleName.asString())
                }
                else -> "%M()" to MemberName(decl.fakePackageName(), "fake${type.toFunName()}")
            }
        }

        /**
         * Appends `return error("...")` to [gFun] — used when an *implicitly* discovered
         * placeholder target ([ToProcess.implicit]) turns out to be unconstructible. The KSP round
         * still succeeds; the error only surfaces if the generated function is ever actually
         * invoked, which should never happen for a discarded `isAny()`-style placeholder.
         */
        private fun addUnconstructibleStub(gFun: FunSpec.Builder, displayName: String, reason: String) {
            gFun.addStatement(
                "return error(%S)",
                "The MocKMP processor could not fake $displayName because $reason. Please register a @FakeProvider function that provides a value of this type."
            )
        }

        /**
         * Resolves one `(format, args)` pair per non-defaulted parameter of constructor [vCstr] of
         * class [vCls] — `null` for nullable parameters, [fakeInitializerOf] otherwise (a builtin
         * placeholder, a `@FakeProvider`, or a nested `fakeXxx()` call; a no-op lambda when the
         * parameter is itself a function type — with an empty body, and no format arg at all, when
         * that lambda's return type is `Unit`, to avoid a "redundant Unit" warning in generated code).
         * Type parameters of [vCls] are substituted using [vType]'s own type arguments, at any depth
         * (see [substituteTypeParameters]) — the very substitution [constructorParamTypeToFake] used
         * to decide which nested `fakeXxx()` functions to generate, so the two must agree. Shared by
         * fake-class generation ([addFakeClassConstructorCall]) and abstract-class mock generation
         * ([addSuperclassConstructorArgs]).
         */
        private fun resolveConstructorArgs(vCls: KSClassDeclaration, vCstr: KSFunctionDeclaration, vType: KSType, filesDeps: MutableSet<KSFile>): List<Pair<String, List<Any>>> {
            val args = ArrayList<Pair<String, List<Any>>>()
            vCstr.parameters.forEach { vParam ->
                if (!vParam.hasDefault) {
                    val vParamType = substituteTypeParameters(vParam.type.resolve(), vCls, vType)
                        ?: error(vParam, "Could not resolve generic parameter $vParam of ${vCls.qualifiedName?.asString()}")
                    if (vParamType.nullability != Nullability.NOT_NULL) {
                        args.add("${vParam.name!!.asString()} = %L" to listOf("null"))
                    } else if (vParamType.isAnyFunctionType) {
                        val vLambdaParams = "_, ".repeat(vParamType.arguments.size - 1)
                        val vReturnType = vParamType.arguments.last().type!!.resolve()
                        if (vReturnType.aliasedDeclaration().qualifiedName?.asString() == "kotlin.Unit") {
                            args.add("${vParam.name!!.asString()} = { $vLambdaParams-> }" to emptyList())
                        } else {
                            val (template, value) = fakeInitializerOf(vReturnType, filesDeps)
                            args.add("${vParam.name!!.asString()} = { $vLambdaParams-> $template }" to listOf(value))
                        }
                    } else {
                        val (template, value) = fakeInitializerOf(vParamType, filesDeps)
                        args.add("${vParam.name!!.asString()} = $template" to listOf(value))
                    }
                }
            }
            return args
        }

        /**
         * Appends `return Xxx(param = ...)` to [gFun] using [resolveConstructorArgs] — or, for an
         * *implicit* target with no public constructor, [addUnconstructibleStub] instead of aborting
         * the KSP round.
         */
        private fun addFakeClassConstructorCall(gFun: FunSpec.Builder, vCls: KSClassDeclaration, vType: KSType, filesDeps: MutableSet<KSFile>, implicit: Boolean) {
            val vCstr = vCls.firstPublicConstructor()
            if (vCstr == null) {
                if (implicit) addUnconstructibleStub(gFun, vCls.qualifiedName?.asString() ?: vCls.simpleName.asString(), "it has no public constructor")
                else error(vCls, "Could not find public constructor for ${vCls.qualifiedName?.asString()}. Please create a @FakeProvider for it.")
                return
            }
            val args = resolveConstructorArgs(vCls, vCstr, vType, filesDeps)
            gFun.addStatement("return %T(${args.joinToString { it.first }})", *(listOf(vCls.toClassName()) + args.flatMap { it.second }).toTypedArray())
        }

        /**
         * Appends `return Xxx.FIRST` to [gFun] — the first declared entry of enum [vCls] — or, for
         * an *implicit* target with no entries, [addUnconstructibleStub] instead of aborting the
         * KSP round.
         */
        private fun addFakeFirstEnumEntry(gFun: FunSpec.Builder, vCls: KSClassDeclaration, implicit: Boolean) {
            val firstEntry = vCls.declarations.filterIsInstance<KSClassDeclaration>().firstOrNull { it.classKind == ClassKind.ENUM_ENTRY }
            if (firstEntry == null) {
                if (implicit) addUnconstructibleStub(gFun, vCls.qualifiedName?.asString() ?: vCls.simpleName.asString(), "it is an empty enum class")
                else error(vCls, "Cannot fake empty enum class ${vCls.qualifiedName!!.asString()}")
                return
            }
            gFun.addStatement("return %T.%L", vCls.toClassName(), firstEntry.simpleName.asString())
        }

        /**
         * Generates the top-level `fakeXxx(): Xxx` function for [vType], into its own file. Sealed
         * classes/interfaces are first resolved to their first constructible permitted subclass, with
         * that subclass's own type arguments (see [resolveSealedTargetType]) — a class fake then
         * constructs the type via
         * [addFakeClassConstructorCall], an enum fake returns its first entry via
         * [addFakeFirstEnumEntry], and an object fake is a plain reference:
         *
         * ```
         * internal fun fakeFoo(): Foo = Foo(bar = "")
         * internal fun fakeDirection(): Direction = Direction.NORTH
         * internal fun fakeSCls(): SCls = SCls.O
         * ```
         *
         * Records the generated function name into [fakes], consumed by [generateFakeAccessor].
         */
        private fun generateFakeFunction(vType: KSType, process: ToProcess) {
            val vCls = vType.declaration as KSClassDeclaration
            val targetType = resolveSealedTargetType(vType)
            val targetCls = targetType.declaration as KSClassDeclaration
            val filesDeps = HashSet(process.files)
            val mockFunName = "fake${vType.toFunName()}"
            val mockPkg = vCls.fakePackageName()
            val gFile = FileSpec.builder(mockPkg, mockFunName)
            val gFun = FunSpec.builder(mockFunName)
                .addModifiers(visibilityModifier)
                .returns(vType.toTypeName(vCls.typeParameters.toTypeParameterResolver()))
            when (targetCls.classKind) {
                ClassKind.CLASS -> addFakeClassConstructorCall(gFun, targetCls, targetType, filesDeps, process.implicit)
                ClassKind.ENUM_CLASS -> addFakeFirstEnumEntry(gFun, targetCls, process.implicit)
                ClassKind.OBJECT -> gFun.addStatement("return %T", targetCls.toClassName())
                else -> {
                    if (process.implicit) addUnconstructibleStub(gFun, vCls.qualifiedName?.asString() ?: vCls.simpleName.asString(), "it is a ${targetCls.classKind.type} that cannot be constructed")
                    else error(vCls, "Cannot process ${targetCls.classKind}")
                }
            }
            gFile.addFunction(gFun.build().also { fakes[vType] = MemberName(mockPkg, mockFunName) })
            gFile.build().writeTo(codeGenerator, Dependencies(true, *filesDeps.toTypedArray()))
        }

        // endregion

        // region Phase 5: injectors

        /**
         * Appends the `@Mock` assignment for [vProp] to [gFun]: a `mockFunctionN(...)` call when
         * [vPropType] is itself a function type (a mocked callback property), or `MockXxx(this)`
         * otherwise.
         */
        private fun addMockInjection(gFun: FunSpec.Builder, vProp: KSPropertyDeclaration, vPropType: KSType) {
            val vPropTypeDecl = vPropType.declaration
            if (vPropType.isFunctionType) {
                val argCount = vPropType.arguments.size - 1
                val args =
                    if (argCount == 0) ""
                    else vPropType.arguments.take(argCount).joinToString(prefix = ", ") { "\"${it.type!!.resolve().declaration.qualifiedName!!.asString()}\"" }
                gFun.addStatement(
                    "receiver.%N = %M(this$args)",
                    vProp.simpleName.asString(),
                    MemberName("org.kodein.mock", "mockFunction$argCount"),
                )
            } else {
                gFun.addStatement(
                    "receiver.%N = %T(this)",
                    vProp.simpleName.asString(),
                    ClassName(vPropTypeDecl.packageName.asString(), vPropTypeDecl.toMockName()),
                )
            }
        }

        /** Appends the `@Fake` assignment for [vProp] to [gFun], via [fakeInitializerOf]. */
        private fun addFakeInjection(gFun: FunSpec.Builder, vProp: KSPropertyDeclaration, vPropType: KSType, filesDeps: MutableSet<KSFile>) {
            val (template, value) = fakeInitializerOf(vPropType, filesDeps)
            gFun.addStatement("receiver.%N = $template", vProp.simpleName.asString(), value)
        }

        /**
         * Every `@Mock`/`@Fake` annotated property that is *visible* on [vCls]: the ones it declares
         * itself, plus the ones it inherits from its supertypes.
         *
         * [toInject] is keyed by declaring class, so without this merge a subclass's injector would
         * set only its own properties — and since the user's `mocker.injectMocks(this)` resolves to
         * the most specific overload, inherited properties would stay uninitialized.
         *
         * Supertypes come first so that, if a subclass shadows an inherited annotated property, the
         * derived declaration is the one kept: the generated `receiver.name = …` always resolves to
         * the most derived property anyway, so entries are deduplicated by simple name, last wins.
         */
        private fun injectedPropertiesOf(vCls: KSClassDeclaration): List<Pair<String, KSPropertyDeclaration>> {
            val ancestors = vCls.getAllSuperTypes()
                .mapNotNull { it.declaration as? KSClassDeclaration }
                .toList()
                .asReversed()
            return (ancestors + vCls)
                .flatMap { toInject[it] ?: emptyList() }
                .associateBy { (_, vProp) -> vProp.simpleName.asString() }
                .values
                .toList()
        }

        /**
         * Generates `Mocker.injectMocks(receiver: Xxx)` for class [vCls], setting every
         * `@Mock`/`@Fake` annotated property visible on it — inherited ones included, see
         * [injectedPropertiesOf]:
         *
         * ```
         * internal fun Mocker.injectMocks(receiver: SomeTests) {
         *     receiver.foo = MockFoo(this)
         *     receiver.bar = fakeBar()
         * }
         * ```
         */
        private fun generateInjector(vCls: KSClassDeclaration) {
            val vProps = injectedPropertiesOf(vCls)
            val filesDeps = HashSet<KSFile>().apply {
                vCls.containingFile?.let { add(it) }
                // An inherited property is declared in another file: its change must retrigger this generation.
                vProps.forEach { (_, vProp) -> vProp.containingFile?.let { add(it) } }
            }

            val gFile = FileSpec.builder(vCls.packageName.asString(), "${vCls.simpleName.asString()}_injectMocks")
            val gFun = FunSpec.builder("injectMocks")
                .addModifiers(visibilityModifier)
                .receiver(mockerTypeName)
                .addParameter("receiver", vCls.toClassName())
            vProps.forEach { (anno, vProp) ->
                val vPropType = vProp.type.resolve()
                when (anno) {
                    ANNOTATION_MOCK -> addMockInjection(gFun, vProp, vPropType)
                    ANNOTATION_FAKE -> addFakeInjection(gFun, vProp, vPropType, filesDeps)
                }
            }
            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true, *filesDeps.toTypedArray()))
        }

        // endregion

        // region Phase 6: accessors

        /**
         * A [FunSpec.Builder] for accessor function [name], with [visibilityModifier] applied and,
         * in multiplatform projects, `actual` — matching the `expect` declaration generated by the
         * MocKMP Gradle plugin (see `mockmp-gradle-plugin/src/main/resources/mockmp.multi.kt`).
         */
        private fun accessorFunBuilder(name: String): FunSpec.Builder {
            val gFun = FunSpec.builder(name).addModifiers(visibilityModifier)
            if (multiplatform) gFun.addModifiers(KModifier.ACTUAL)
            return gFun
        }

        /**
         * Generates the `Mocker.mock(KClass<T>): T` dispatcher, with one `when` branch per mocked
         * interface:
         *
         * ```
         * internal actual fun <T : Any> Mocker.mock(type: KClass<T>): T = when (type) {
         *     Foo::class -> MockFoo(this) as T
         *     else -> error("Could not find mock for type $type")
         * }
         * ```
         */
        private fun generateMockAccessor() {
            @Suppress("LocalVariableName")
            val T = TypeVariableName("T", Any::class)
            val gFile = FileSpec.builder(accessorsPackage, "mocks")
            val gFun = accessorFunBuilder("mock")
                .receiver(mockerTypeName)
                .addParameter("type", KClass::class.asTypeName().parameterizedBy(T))
                .addTypeVariable(T)
                .returns(T)

            if (mocks.isNotEmpty()) {
                gFun.addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build())
                gFun.beginControlFlow("return when (type)")
                mocks.forEach { (itf, mock) ->
                    val mockTypeName: TypeName =
                        if (itf.typeParameters.isNotEmpty()) {
                            mock.parameterizedBy(*itf.typeParameters.map { it.bounds.first().resolve().toTypeName() }.toTypedArray())
                        } else {
                            mock
                        }
                    gFun.addStatement("%T::class -> %T(this) as T", itf.toClassName(), mockTypeName)
                }
                gFun.addStatement("else -> error(\"Could not find mock for type \$type\")")
                gFun.endControlFlow()
            } else {
                gFun.addStatement("error(\"No mocks declared\")")
            }

            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        /**
         * Generates the `fake(KType): T` dispatcher, with one `when` branch per faked type, keyed
         * by a generated `private val type_pkg_Xxx: KType = typeOf<Xxx>()` (faked types can be
         * generic, and `KType` equality — unlike [KClass] — accounts for type arguments). The
         * package is folded into the name (via [toFunName]) because every one of these properties
         * lives in the same generated `fakes.kt` file, where a bare simple name is not unique
         * (`foo.Data` and `bar.Data` would otherwise both want `type_Data`):
         *
         * ```
         * private val type_foo_Foo: KType = typeOf<foo.Foo>()
         * internal actual fun <T : Any> fake(type: KType): T = when (type) {
         *     type_foo_Foo -> fakefoo_Foo() as T
         *     else -> error("Could not find fake for type $type")
         * }
         * ```
         */
        private fun generateFakeAccessor() {
            @Suppress("LocalVariableName")
            val T = TypeVariableName("T", Any::class)
            val gFile = FileSpec.builder(accessorsPackage, "fakes")
            fakes.forEach { (type, _) ->
                gFile.addProperty(
                    PropertySpec.builder("type_${type.toFunName()}", KType::class)
                        .addModifiers(KModifier.PRIVATE)
                        .initializer("%M<%T>()", MemberName("kotlin.reflect", "typeOf"), type.toTypeName())
                        .build()
                )
            }
            val gFun = accessorFunBuilder("fake")
                .addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build())
                .addParameter("type", KType::class.asTypeName())
                .addTypeVariable(T)
                .returns(T)

            if (fakes.isNotEmpty()) {
                gFun.beginControlFlow("return when (type)")
                fakes.forEach { (type, fake) -> gFun.addStatement("type_${type.toFunName()} -> %M() as T", fake) }
                gFun.addStatement("else -> error(\"Could not find fake for type \$type\")")
                gFun.endControlFlow()
            } else {
                gFun.addStatement("error(\"No fakes declared\")")
            }
            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        /**
         * Generates the `Mocker.injectMocks(receiver: Any)` dispatcher, with one `when` branch per
         * class that has injected properties:
         *
         * ```
         * internal actual fun Mocker.injectMocks(receiver: Any) = when (receiver) {
         *     is SomeTests -> injectMocks(receiver)
         *     else -> error("Could not find injector for $receiver")
         * }
         * ```
         *
         * Only the first matching branch of a `when` ever runs, so branches are ordered most derived
         * first: a class always has strictly more supertypes than any of its own supertypes, which
         * makes "supertype count, descending" a valid topological order. Unrelated classes are then
         * ordered by qualified name, so the generated file does not depend on [toInject]'s hash order.
         */
        private fun generateInjectorAccessor() {
            val gFile = FileSpec.builder(accessorsPackage, "injectors")
            val gFun = accessorFunBuilder("injectMocks")
                .receiver(mockerTypeName)
                .addParameter("receiver", Any::class)

            if (toInject.isNotEmpty()) {
                val sorted = toInject.keys.sortedWith(
                    compareByDescending<KSClassDeclaration> { it.getAllSuperTypes().count() }
                        .thenBy { it.qualifiedName?.asString() ?: it.simpleName.asString() }
                )
                gFun.beginControlFlow("return when (receiver)")
                sorted.forEach { cls -> gFun.addStatement("is %T -> %M(receiver)", cls.toClassName(), MemberName(cls.packageName.asString(), "injectMocks")) }
                gFun.addStatement("else -> error(\"Could not find injector for \$receiver\")")
                gFun.endControlFlow()
            } else {
                gFun.addStatement("error(\"No injectors declared\")")
            }
            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        /**
         * Generates the `providePlaceholder(KClass<*>): Any` dispatcher — the replacement for the
         * unsafe-cast placeholder mechanism this used to rely on. Every generated `MockXxx` class
         * registers this on its `mocker` (see [mockClassBuilder]'s `init` block), so it's what
         * `References` falls back to when it has no builtin and no user-registered reference for a
         * type — i.e. what `isAny()`/`isEqual()`/etc. need to return from inside an `every { }`.
         *
         * One `when` branch per: mocked interface/abstract class (`MockFoo(Mocker())`), fake
         * class/enum (`fakeFoo()`, deduped to one representative per raw class since `KClass`
         * erases generic type arguments — see [fakes]), concrete array type (see
         * [placeholderArrayTypes] — `Array<T>` is the one case that *isn't* erased on the JVM),
         * function-type arity (a plain lambda cast to the right shape, matched by the same raw
         * `Function1::class`/etc. `T::class` already erases to — see [placeholderFunctionShapes];
         * one branch per `KClass`, a suspend shape's JVM fallback key never displacing a genuine one),
         * and non-numeric builtin (a literal or factory call matching [builtins] — the numeric ones
         * are already handled by `References`'s own hardcoded primitive map and never reach here):
         *
         * ```
         * internal actual fun providePlaceholder(cls: KClass<*>): Any = when (cls) {
         *     Bar::class -> MockBar(Mocker())
         *     Function1::class -> ({ _ -> error("...") }) as (Any?) -> Any?
         *     Data::class -> fakeData()
         *     String::class -> ""
         *     else -> error("Could not find placeholder for type $cls")
         * }
         * ```
         */
        private fun generatePlaceholderAccessor() {
            val gFile = FileSpec.builder(accessorsPackage, "placeholders")
            val gFun = accessorFunBuilder("providePlaceholder")
                .addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build())
                .addParameter("cls", KClass::class.asTypeName().parameterizedBy(STAR))
                .returns(Any::class)

            gFun.beginControlFlow("return when (cls)")

            mocks.forEach { (itf, mock) ->
                val mockTypeName: TypeName =
                    if (itf.typeParameters.isNotEmpty()) {
                        mock.parameterizedBy(*itf.typeParameters.map { it.bounds.first().resolve().toTypeName() }.toTypedArray())
                    } else {
                        mock
                    }
                gFun.addStatement("%T::class -> %T(%T())", itf.toClassName(), mockTypeName, mockerTypeName)
            }

            // A fake keyed by a sealed type (e.g. SItf) is generated by constructing a concrete
            // permitted subclass (SItf.C — see resolveSealedTarget). Register both KClasses against
            // the same function: isAny<SItf>() asks for the former, isInstanceOf<SItf.C>() the latter.
            val fakesByDecl = LinkedHashMap<KSClassDeclaration, MemberName>()
            fakes.forEach { (type, member) ->
                val decl = type.declaration as? KSClassDeclaration ?: return@forEach
                fakesByDecl.getOrPut(decl) { member }
                val target = resolveSealedTarget(decl)
                if (target != decl) fakesByDecl.getOrPut(target) { member }
            }
            fakesByDecl.forEach { (decl, member) -> gFun.addStatement("%T::class -> %M()", decl.toClassName(), member) }

            // isInstanceOf<T>()/isEqual<T>() can also target one of a sealed type's OTHER permitted
            // subclasses — not just the one resolveSealedTarget picked for the fake function above.
            // An object subclass needs no function call at all: just reference the singleton.
            val sealedObjectSubclasses = LinkedHashSet<KSClassDeclaration>()
            fakes.keys.mapNotNull { it.declaration as? KSClassDeclaration }
                .filter { Modifier.SEALED in it.modifiers }
                .forEach { sealed -> sealed.getSealedSubclasses().forEach { sub -> if (sub.classKind == ClassKind.OBJECT) sealedObjectSubclasses += sub } }
            sealedObjectSubclasses.forEach { obj -> gFun.addStatement("%T::class -> %T", obj.toClassName(), obj.toClassName()) }

            builtins.entries.filter { !it.key.startsWith("java.") }.forEach { (qualifiedName, templateValue) ->
                val (template, value) = templateValue
                // Unlike fakeInitializerOf's use of these same templates (always in a context with a
                // known target type, e.g. a named constructor argument), this `when` branch's target
                // type is just `Any` — none of these generic factories (constructors or top-level
                // `emptyXxx()`/`emptyArray()` functions alike) can infer a type argument there.
                val typeArgArity = when (qualifiedName) {
                    "kotlin.collections.Map", "kotlin.collections.HashMap", "kotlin.collections.LinkedHashMap" -> 2
                    else -> if (template == "%M()") 1 else 0
                }
                val placeholderTemplate =
                    if (typeArgArity > 0) "%M<${List(typeArgArity) { "Any?" }.joinToString(", ")}>()" else template
                val pkg = qualifiedName.substringBeforeLast('.')
                val simple = qualifiedName.substringAfterLast('.')
                gFun.addStatement("%T::class -> $placeholderTemplate", ClassName(pkg, simple), value)
            }

            placeholderArrayTypes.forEach { arrType ->
                val componentType = arrType.arguments.first().type!!.resolve().toTypeName()
                val emptyArray = MemberName("kotlin", "emptyArray")
                // A type literal with an explicit type argument (`Array<String>::class`) is JVM-only
                // syntax — Kotlin/Native's parser rejects it outright. An instance-based class
                // literal (the class of an actual, constructed array) works identically everywhere,
                // and — on the JVM specifically — still resolves to the same component-type-specific
                // KClass that `Array<String>::class` would, since JVM arrays reify their component
                // type regardless of how their class is obtained.
                gFun.addStatement("%M<%T>()::class -> %M<%T>()", emptyArray, componentType, emptyArray, componentType)
            }

            // One branch per KClass, since only the first matching one of a `when` ever runs.
            // Every shape claims the declaration KSP resolved it to, and a suspend shape *also* wants
            // `Function<arity+1>::class` (see below) — a key a genuine, non-suspend shape one arity
            // higher may already own. The genuine shape wins: it is the only value that key can be
            // looked up with anywhere except the JVM, and on the JVM erasure makes either lambda
            // satisfy the cast. Registering the fallbacks in a second pass is what enforces that,
            // whatever order the shapes were discovered in.
            val functionShapeBranches = LinkedHashMap<ClassName, Pair<Boolean, Int>>()
            placeholderFunctionShapes.forEach { (decl, isSuspendAndArity) ->
                // Same declaration KSP itself resolved the type to — same as any other interface's
                // `Bar::class` branch.
                functionShapeBranches[decl.toClassName()] = isSuspendAndArity
            }
            placeholderFunctionShapes.values.forEach { isSuspendAndArity ->
                val (isSuspend, arity) = isSuspendAndArity
                if (isSuspend) {
                    // On the JVM specifically, a reified suspend function type's runtime class is its
                    // CPS-transformed backing type (Function(arity+1), continuation appended), not the
                    // frontend-level SuspendFunctionN declaration KSP resolves above — Native's and
                    // Wasm's own reification, unlike the JVM's, does match the frontend declaration.
                    // Since a suspend-shaped lambda genuinely implements both on the JVM, adding this
                    // second branch covers both platforms' actual runtime lookup key.
                    functionShapeBranches.getOrPut(ClassName("kotlin", "Function${arity + 1}")) { isSuspendAndArity }
                }
            }

            functionShapeBranches.forEach { (branchClass, isSuspendAndArity) ->
                val (isSuspend, arity) = isSuspendAndArity
                val shape = buildString {
                    if (isSuspend) append("suspend ")
                    append("(")
                    append(List(arity) { "Any?" }.joinToString(", "))
                    append(") -> Any?")
                }
                // Explicitly typed: JS/Wasm, unlike JVM/Native, don't infer untyped `_` lambda
                // parameters from the surrounding `as Shape` cast.
                val params = if (arity == 0) "" else List(arity) { "_: Any?" }.joinToString(", ") + " -> "
                val message = "The MocKMP processor could not create a placeholder for this function type."
                // A declared-type local val, not a post-hoc `as` cast: a bare lambda literal is
                // always compiled non-suspend, and casting it afterwards is a genuine (failing) cast
                // for a suspend shape, not a no-op — the lambda has to be compiled *as* the target
                // shape from the start, which only a declared-type context (not `as`) provides.
                val value = "run { val f: $shape = { ${params}error(%S) }; f }"
                gFun.addStatement("%T::class -> $value", branchClass, message)
            }

            gFun.addStatement("else -> error(\"Could not find placeholder for type \$cls\")")
            gFun.endControlFlow()

            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        // endregion
    }
}
