package org.kodein.mock.ksp

import com.google.devtools.ksp.containingFile
import com.google.devtools.ksp.isAbstract
import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.*
import kotlin.reflect.KClass
import kotlin.reflect.KType


/**
 * KSP [SymbolProcessor] that powers MocKMP code generation.
 *
 * Each processing round ([process]) scans the module for MocKMP annotations and emits three kinds
 * of files, in this order:
 *
 * - **Mocks**: for every interface referenced by `@Mock` or `@UsesMocks(...)`, a `MockXxx` class
 *   implementing it, delegating every member to an injected [org.kodein.mock.Mocker]
 *   (see [Round.generateMockClass]).
 * - **Fakes**: for every type referenced by `@Fake`, `@UsesFakes(...)`, or transitively required
 *   as a non-nullable, non-defaulted constructor parameter of another fake, a top-level
 *   `fakeXxx(): Xxx` function that builds a placeholder instance (see [Round.generateFakeFunction]).
 * - **Injectors**: for every class with `@Mock`/`@Fake` annotated properties, a
 *   `Mocker.injectMocks(receiver: Xxx)` function that sets them all (see [Round.generateInjector]).
 *
 * Once at least one mock or fake exists, three small dispatch functions are additionally emitted
 * into [accessorsPackage] — `Mocker.mock(KClass<T>): T`, `fake(KType): T` and
 * `Mocker.injectMocks(Any)` — matching the `expect` declarations generated by the MocKMP Gradle
 * plugin (see `mockmp-gradle-plugin/src/main/resources/mockmp.multi.kt`).
 *
 * The whole pipeline for a single round is implemented by [Round], instantiated fresh on every
 * [process] call so this processor itself carries no state between rounds.
 */
public class MocKMPProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val throwErrors: Boolean,
    public: Boolean,
    private val accessorsPackage: String,
    private val multiplatform: Boolean,
) : SymbolProcessor {

    private companion object {
        val mockerTypeName = ClassName("org.kodein.mock", "Mocker")

        // Fully-qualified names of the annotations MocKMP looks for.
        const val ANNOTATION_MOCK = "org.kodein.mock.Mock"
        const val ANNOTATION_FAKE = "org.kodein.mock.Fake"
        const val ANNOTATION_USES_MOCKS = "org.kodein.mock.UsesMocks"
        const val ANNOTATION_USES_FAKES = "org.kodein.mock.UsesFakes"
        const val ANNOTATION_FAKE_PROVIDER = "org.kodein.mock.FakeProvider"

        /**
         * Types for which a literal placeholder can be emitted directly instead of generating (or
         * looking up) a `fakeXxx()` function. Maps a type's qualified name to a KotlinPoet format
         * string and its single format argument (a literal, or a [MemberName] to a factory function).
         */
        val builtins = mapOf(
            "kotlin.Unit" to ("%L" to "Unit"),
            "kotlin.Boolean" to ("%L" to "false"),
            "kotlin.Byte" to ("%L" to "0"),
            "kotlin.Short" to ("%L" to "0"),
            "kotlin.Int" to ("%L" to "0"),
            "kotlin.Long" to ("%L" to "0L"),
            "kotlin.Float" to ("%L" to "0f"),
            "kotlin.Double" to ("%L" to "0.0"),
            "kotlin.String" to ("%L" to "\"\""),
            "kotlin.collections.List" to ("%M()" to MemberName("kotlin.collections", "emptyList")),
            "kotlin.collections.ArrayList" to ("%M()" to MemberName("kotlin.collections", "ArrayList")),
            "java.util.ArrayList" to ("%M()" to MemberName("kotlin.collections", "ArrayList")),
            "kotlin.collections.ArrayDeque" to ("%M()" to MemberName("kotlin.collections", "ArrayDeque")),
            "kotlin.collections.Set" to ("%M()" to MemberName("kotlin.collections", "emptySet")),
            "kotlin.collections.HashSet" to ("%M()" to MemberName("kotlin.collections", "HashSet")),
            "java.util.HashSet" to ("%M()" to MemberName("kotlin.collections", "HashSet")),
            "kotlin.collections.LinkedHashSet" to ("%M()" to MemberName("kotlin.collections", "LinkedHashSet")),
            "java.util.LinkedHashSet" to ("%M()" to MemberName("kotlin.collections", "LinkedHashSet")),
            "kotlin.collections.Map" to ("%M()" to MemberName("kotlin.collections", "emptyMap")),
            "kotlin.collections.HashMap" to ("%M()" to MemberName("kotlin.collections", "HashMap")),
            "java.util.HashMap" to ("%M()" to MemberName("kotlin.collections", "HashMap")),
            "kotlin.collections.LinkedHashMap" to ("%M()" to MemberName("kotlin.collections", "LinkedHashMap")),
            "java.util.LinkedHashMap" to ("%M()" to MemberName("kotlin.collections", "LinkedHashMap")),
            "kotlin.Array" to ("%M()" to MemberName("kotlin", "emptyArray"))
        )
    }

    private val KSType.isAnyFunctionType get() = isFunctionType || isSuspendFunctionType

    private val visibilityModifier = if (public) KModifier.PUBLIC else KModifier.INTERNAL

    /** Thrown to abort processing of the current round with a location-tagged message. */
    private class Error(message: String, val node: KSNode) : Exception(message)

    override fun process(resolver: Resolver): List<KSAnnotated> =
        try {
            Round(resolver).run()
        } catch (e: Error) {
            logger.error("MocKMP: ${e.message}", e.node)
            if (throwErrors) throw e
            emptyList()
        }

    // region Error reporting

    /** Renders [this] node as a human-readable path, for messages when no [FileLocation] is available. */
    private fun KSNode.asString(): String = when (this) {
        is KSValueParameter -> {
            val nameStr = name?.asString() ?: "?"
            if (parent != null) "${parent!!.asString()}($nameStr)"
            else nameStr
        }
        is KSClassDeclaration -> this.qualifiedName?.asString() ?: this.simpleName.asString()
        else -> (parent?.let { it.asString() + "." } ?: "") + toString()
    }

    /** Fails the current round with [message], pointing [logger] at [node]'s source location when known. */
    private fun error(node: KSNode, message: String): Nothing {
        val prefix = when (val loc = node.location) {
            is FileLocation -> "$node (${loc.filePath}:${loc.lineNumber})"
            is NonExistLocation -> node.asString()
        }
        throw Error("$prefix: $message", node)
    }

    // endregion

    /** The files and annotation sites that referenced a to-be-generated mock or fake, accumulated across annotations. */
    private class ToProcess {
        val files = HashSet<KSFile>()
        val references = HashSet<KSNode>()
    }

    // region Naming

    /** The `Outer_Inner_` prefix identifying [this] declaration's chain of enclosing declarations, if any. */
    private fun KSDeclaration.parentPrefix(): String = buildString {
        var pDecl = parentDeclaration
        while (pDecl != null) {
            append(pDecl.simpleName.asString())
            append("_")
            pDecl = pDecl.parentDeclaration
        }
    }

    /**
     * A name-safe identifier for the `fakeXxx()` function generated for [this] type: unique per
     * distinct type argument list (`fakeGenDataXIntX`, `fakeGenDataXStringX`, ...), nesting
     * (`fakeFakeTests_FakeAny` for a nested class `FakeAny` inside `FakeTests`) and nullability.
     */
    private fun KSType.toFunName(): String {
        val prefix = (if (isMarkedNullable) "Nul" else "") + declaration.parentPrefix()
        return prefix +
                if (arguments.isEmpty()) declaration.simpleName.asString()
                else "${declaration.simpleName.asString()}X${
                    arguments.joinToString("_") {
                        if (it.variance == Variance.STAR) "STAR"
                        else it.type!!.resolve().toFunName()
                    }
                }X"
    }

    /** The `MockXxx` class name generated for [this] mocked interface. */
    private fun KSDeclaration.toMockName(): String = "Mock" + parentPrefix() + simpleName.asString()

    /**
     * The package a generated `fakeXxx()` function for [this] declaration is emitted into: its own
     * package, except for Kotlin stdlib packages (which this module cannot write into), redirected
     * under a local `fake.` prefix.
     */
    private fun KSDeclaration.fakePackageName(): String =
        if (packageName.isKotlinStdlib()) "fake." + packageName.asString() else packageName.asString()

    // endregion

    /**
     * Mutable state and generation logic of a single KSP processing round. A fresh instance is
     * created per [process] call, so [MocKMPProcessor] itself carries no state across rounds.
     */
    private inner class Round(private val resolver: Resolver) {

        /** Interfaces referenced by `@Mock`/`@UsesMocks`, with the files/nodes that referenced them. */
        private val toMock = HashMap<KSClassDeclaration, ToProcess>()

        /** Generated `MockXxx` class name, per mocked interface — consumed by [generateMockAccessor]. */
        private val mocks = HashMap<KSClassDeclaration, ClassName>()

        /** Types referenced by `@Fake`/`@UsesFakes`, or required transitively (see [expandTransitiveFakes]). */
        private val toFake = HashMap<KSType, ToProcess>()

        /** Generated `fakeXxx()` function name, per faked type — consumed by [generateFakeAccessor]. */
        private val fakes = HashMap<KSType, MemberName>()

        /** User-supplied `@FakeProvider` functions, keyed by the type they provide a fake for. */
        private val providedFakes = HashMap<KSType, KSFunctionDeclaration>()

        /** Properties annotated `@Mock`/`@Fake`, grouped by enclosing class — consumed by [generateInjector]. */
        private val toInject = HashMap<KSClassDeclaration, ArrayList<Pair<String, KSPropertyDeclaration>>>()

        /** Runs the full pipeline for this round: collect, expand, then generate every kind of file. */
        fun run(): List<KSAnnotated> {
            collectAnnotatedSymbols()
            collectFakeProviders()
            expandTransitiveFakes()

            toMock.forEach { (vItf, process) -> generateMockClass(vItf, process) }
            toFake.forEach { (vType, process) -> generateFakeFunction(vType, process) }
            toInject.forEach { (vCls, vProps) -> generateInjector(vCls, vProps) }

            if (mocks.isNotEmpty() || fakes.isNotEmpty()) {
                generateMockAccessor()
                generateFakeAccessor()
                generateInjectorAccessor()
            }

            return emptyList()
        }

        // region Phase 1: collect annotated symbols

        /** Registers [type] as needing a `MockXxx` class, or fails if it isn't a mockable interface. */
        private fun addMock(type: KSType, files: Iterable<KSFile>, node: KSNode) {
            if (type.isFunctionType) return
            val decl = type.declaration
            if (decl !is KSClassDeclaration || decl.classKind != ClassKind.INTERFACE) error(node, "Cannot generate mock for non interface $decl")
            toMock.getOrPut(decl) { ToProcess() }.let {
                it.files.addAll(files)
                it.references.add(node)
            }
        }

        /** Registers [type] as needing a `fakeXxx()` function, or fails if it isn't a fakeable class/enum. */
        private fun addFake(type: KSType, files: Iterable<KSFile>, node: KSNode) {
            val decl = type.declaration

            if (decl !is KSClassDeclaration) {
                error(node, "Cannot generate fake for ${decl.javaClass.simpleName} ${decl.qualifiedName?.asString() ?: decl.simpleName.asString()}")
            }
            if (decl.isAbstract() || decl.classKind !in arrayOf(ClassKind.CLASS, ClassKind.ENUM_CLASS)) {
                error(node, "Cannot generate fake for ${if (decl.isAbstract()) "abstract " else ""}${decl.classKind.type} ${decl.qualifiedName?.asString() ?: decl.simpleName.asString()}")
            }
            toFake.getOrPut(type) { ToProcess() }.let {
                it.files.addAll(files)
                it.references.add(node)
            }
        }

        /** Finds every property annotated [annotationName] (or its setter), registers its class for injection, and [add]s its type. */
        private fun lookUpFields(annotationName: String, add: (KSType, Iterable<KSFile>, KSNode) -> Unit) {
            val symbols = resolver.getSymbolsWithAnnotation(annotationName)
            symbols.forEach { symbol ->
                val prop = when (symbol) {
                    is KSPropertySetter -> symbol.receiver
                    is KSPropertyDeclaration -> {
                        if (!symbol.isMutable) error(symbol, "$symbol is immutable but is annotated with @${annotationName.split(".").last()}")
                        symbol
                    }
                    else -> error(symbol, "$symbol is not a property nor a property setter but is annotated with @${annotationName.split(".").last()} (is ${symbol::class.simpleName})")
                }
                val cls = prop.parentDeclaration as? KSClassDeclaration ?: error(symbol, "Cannot generate injector for $prop as it is not inside a class")
                toInject.getOrPut(cls) { ArrayList() }.add(annotationName to prop)
                add(prop.type.resolve(), listOf(cls.containingFile!!), symbol)
            }
        }

        /** Finds every declaration annotated `@UsesMocks(...)`/`@UsesFakes(...)` and [add]s each type listed in [annotationName]'s array argument. */
        private fun lookUpUses(annotationName: String, add: (KSType, Iterable<KSFile>, KSNode) -> Unit) {
            val uses = resolver.getSymbolsWithAnnotation(annotationName)
            uses.forEach { use ->
                val anno = use.annotations.first { it.annotationType.resolve().declaration.qualifiedName!!.asString() == annotationName }
                (anno.arguments.first().value as List<*>).forEach {
                    add((it as KSType), listOf(use.containingFile!!), use)
                }
            }
        }

        /** Populates [toMock], [toFake] and [toInject] from `@Mock`, `@Fake`, `@UsesMocks` and `@UsesFakes`. */
        private fun collectAnnotatedSymbols() {
            lookUpFields(ANNOTATION_MOCK, ::addMock)
            lookUpFields(ANNOTATION_FAKE, ::addFake)
            lookUpUses(ANNOTATION_USES_MOCKS, ::addMock)
            lookUpUses(ANNOTATION_USES_FAKES, ::addFake)
        }

        /**
         * Populates [providedFakes] from `@FakeProvider` top-level functions, and removes their
         * return type from [toFake] — a user-supplied provider makes generation unnecessary.
         */
        private fun collectFakeProviders() {
            resolver.getSymbolsWithAnnotation(ANNOTATION_FAKE_PROVIDER).forEach {
                if (it !is KSFunctionDeclaration || it.parent !is KSFile) error(it, "Only top-level functions can be annotated with @FakeProvider")
                val type = it.returnType!!.resolve()
                val typeDeclaration = type.declaration
                if (typeDeclaration !is KSClassDeclaration) error(it, "@FakeProvider functions must return class types.")
                if (type in providedFakes) error(it, "Only one @FakeProvider function must exist for this type (other is ${providedFakes[type]!!.asString()}).")
                toFake.remove(type)
                providedFakes[type] = it
            }
        }

        // endregion

        // region Phase 2: transitive fakes

        /**
         * Resolves the type a fake is needed for, for constructor [param] of fake class [vCls]
         * (whose fake is being generated for [vType]) — or `null` if [param] needs no fake: it has
         * a default value, is nullable, resolves to a [builtins] type, or already has one
         * ([providedFakes] or [toFake]).
         *
         * NOTE: unwraps function types *then* substitutes type parameters; the constructor-argument
         * generation in [addFakeClassConstructorCall] resolves the same kind of parameter in the
         * opposite order. The two are independent and are intentionally not merged here.
         */
        private fun constructorParamTypeToFake(vCls: KSClassDeclaration, vType: KSType, param: KSValueParameter, process: ToProcess): KSType? {
            if (param.hasDefault) return null
            var paramTypeRef = param.type
            var paramType = paramTypeRef.resolve()
            if (paramType.nullability != Nullability.NOT_NULL) return null

            if (paramType.isAnyFunctionType) {
                paramTypeRef = paramType.arguments.last().type!!
                paramType = paramTypeRef.resolve()
            }
            if (paramType.declaration is KSTypeParameter) {
                val index = vCls.typeParameters.indexOf(paramType.declaration)
                paramTypeRef = vType.arguments.getOrNull(index)?.type
                    ?: error(param, "Could not resolve generic parameter $param (${process.references.firstOrNull()?.location})")
                paramType = paramTypeRef.resolve()
            }
            val paramTypeName = paramTypeRef.toRealTypeName(vCls.typeParameters.toTypeParameterResolver())
            return paramType.takeIf { paramTypeName.qualified() !in builtins && it !in providedFakes && it !in toFake }
        }

        /**
         * Breadth-first expansion of [toFake]: a fake class may itself require fakes for its own
         * constructor parameter types (a `data class Foo(val bar: Bar)` needs `fakeBar()` too), so
         * this walks the constructor graph and adds any parameter type not already covered.
         */
        private fun expandTransitiveFakes() {
            val toExplore = ArrayDeque(toFake.map { it.toPair() })
            while (toExplore.isNotEmpty()) {
                val (type, process) = toExplore.removeFirst()
                val cls = type.declaration as KSClassDeclaration
                cls.firstPublicConstructor()?.parameters?.forEach { param ->
                    val paramTypeToFake = constructorParamTypeToFake(cls, type, param, process) ?: return@forEach
                    addFake(paramTypeToFake, process.files, param)
                    toExplore.add(paramTypeToFake to process)
                }
            }
        }

        // endregion

        // region Phase 3: mock generation

        /** Builds the `MockXxx` class shell for [vItf]: superinterface, type variables, and the private `mocker` constructor property. */
        private fun mockClassBuilder(vItf: KSClassDeclaration, mockClassName: String): Pair<TypeSpec.Builder, PropertySpec> {
            val gCls = TypeSpec.classBuilder(mockClassName)
                .addSuperinterface(
                    if (vItf.typeParameters.isEmpty()) vItf.toClassName()
                    else vItf.toClassName().parameterizedBy(vItf.typeParameters.map { it.toTypeVariableName() })
                )
                .addModifiers(visibilityModifier)
            vItf.typeParameters.forEach { vParam -> gCls.addTypeVariable(vParam.toTypeVariableName()) }
            gCls.primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("mocker", mockerTypeName)
                    .build()
            )
            val mocker = PropertySpec.builder("mocker", mockerTypeName)
                .initializer("mocker")
                .addModifiers(KModifier.PRIVATE)
                .build()
            gCls.addProperty(mocker)
            return gCls to mocker
        }

        /**
         * The [org.kodein.mock.Mocker]-backed override for one abstract property of the mocked
         * interface, e.g. for `val bar: String` and mutable `var baz: Int`:
         *
         * ```
         * override val bar: String get() = this.mocker.register(this, "get:bar")
         * override var baz: Int
         *     get() = this.mocker.register(this, "get:baz")
         *     set(value) { this.mocker.register(this, "set:baz", value) }
         * ```
         */
        private fun mockedProperty(vProp: KSPropertyDeclaration, vItf: KSClassDeclaration, mocker: PropertySpec): PropertySpec {
            val typeParamResolver = vProp.typeParameters.toTypeParameterResolver(vItf.typeParameters.toTypeParameterResolver())
            val gPropType = vProp.type.toTypeName(typeParamResolver)
            val gProp = PropertySpec.builder(vProp.simpleName.asString(), gPropType)
                .addModifiers(KModifier.OVERRIDE)
                .getter(
                    FunSpec.getterBuilder()
                        .addStatement("return this.%N.register(this, %S)", mocker, "get:${vProp.simpleName.asString()}")
                        .build()
                )
            vProp.annotations.forEach { gProp.addAnnotation(it.toAnnotationSpec()) }
            if (vProp.isMutable) {
                gProp.mutable(true)
                    .setter(
                        FunSpec.setterBuilder()
                            .addParameter("value", gPropType)
                            .addStatement("return this.%N.register(this, %S, value)", mocker, "set:${vProp.simpleName.asString()}")
                            .build()
                    )
            }
            return gProp.build()
        }

        /**
         * The `"name(kotlin.Int, vararg kotlin.String)"` key computed for [vFun] — the same key
         * [org.kodein.mock.Mocker.register]/`registerSuspend` receive as `method`, and that
         * `every { }` blocks match recorded calls against.
         */
        private fun registrationKey(vFun: KSFunctionDeclaration): String {
            val paramsDescription = vFun.parameters.joinToString {
                (it.type.resolve().declaration as? KSClassDeclaration)?.qualifiedName?.asString()?.let { str ->
                    if (it.isVararg) "vararg $str" else str
                } ?: "?"
            }
            return "${vFun.simpleName.asString()}($paramsDescription)"
        }

        /**
         * The [org.kodein.mock.Mocker]-backed override for one function of the mocked interface,
         * e.g. for `fun baz(i: Int): String`:
         *
         * ```
         * override fun baz(i: Int): String = this.mocker.register(this, "baz(kotlin.Int)", i)
         * ```
         *
         * Non-abstract (default) interface members get a `default = { super.baz(i) }` fallback, so
         * that mocking them with `every { }` remains optional.
         */
        private fun mockedFunction(vFun: KSFunctionDeclaration, vItf: KSClassDeclaration, mocker: PropertySpec): FunSpec {
            val gFun = FunSpec.builder(vFun.simpleName.asString())
                .addModifiers(KModifier.OVERRIDE)
            val typeParamResolver = vFun.typeParameters.toTypeParameterResolver(vItf.typeParameters.toTypeParameterResolver())
            vFun.typeParameters.forEach { vParam -> gFun.addTypeVariable(vParam.toTypeVariableName(typeParamResolver)) }
            gFun.addModifiers((vFun.modifiers - Modifier.ABSTRACT - Modifier.OPEN - Modifier.OPERATOR).mapNotNull { it.toKModifier() })
            gFun.returns(vFun.returnType!!.toTypeName(typeParamResolver))
            vFun.annotations.forEach { gFun.addAnnotation(it.toAnnotationSpec()) }
            vFun.parameters.forEach { vParam ->
                gFun.addParameter(vParam.name!!.asString(), vParam.type.toTypeName(typeParamResolver), if (vParam.isVararg) listOf(KModifier.VARARG) else emptyList())
            }
            val paramsCall = if (vFun.parameters.isEmpty()) "" else vFun.parameters.joinToString { it.name!!.asString() }
            val register = if (Modifier.SUSPEND in vFun.modifiers) "registerSuspend" else "register"
            val default = if (vFun.isAbstract) "" else "default = { super.${vFun.simpleName.asString()}($paramsCall) }"
            gFun.addStatement(
                "return this.%N.$register(this, %S${paramsCall.withNonEmptyPrefix(", ")}${default.withNonEmptyPrefix(", ")})",
                mocker,
                registrationKey(vFun)
            )
            return gFun.build()
        }

        /**
         * Generates the `MockXxx` class implementing interface [vItf], into its own file, e.g. for
         * `interface Foo { val bar: String; fun baz(i: Int): String }`:
         *
         * ```
         * internal class MockFoo(mocker: Mocker) : Foo {
         *     private val mocker: Mocker = mocker
         *     override val bar: String get() = this.mocker.register(this, "get:bar")
         *     override fun baz(i: Int): String = this.mocker.register(this, "baz(kotlin.Int)", i)
         * }
         * ```
         *
         * Records the generated class name into [mocks], consumed by [generateMockAccessor].
         */
        private fun generateMockClass(vItf: KSClassDeclaration, process: ToProcess) {
            val mockClassName = vItf.toMockName()
            val gFile = FileSpec.builder(vItf.packageName.asString(), mockClassName)
            val (gCls, mocker) = mockClassBuilder(vItf, mockClassName)

            vItf.getAllProperties()
                .filter { it.isAbstract() }
                .forEach { vProp -> gCls.addProperty(mockedProperty(vProp, vItf, mocker)) }

            vItf.getAllFunctions()
                .filter { it.simpleName.asString() !in listOf("equals", "hashCode") }
                .forEach { vFun -> gCls.addFunction(mockedFunction(vFun, vItf, mocker)) }

            gFile.addType(gCls.build().also { mocks[vItf] = ClassName(vItf.packageName.asString(), it.name!!) })
            gFile.build().writeTo(codeGenerator, Dependencies(true, *process.files.toTypedArray()))
        }

        // endregion

        // region Phase 4: fake generation

        /**
         * Resolves how to initialize a value of [type], as a KotlinPoet `(format, arg)` pair
         * suitable for `addStatement("... $template ...", ..., value)`:
         *  1. a [builtins] literal or factory call, if [type] (after unwrapping any type alias) is one;
         *  2. a call to the user's `@FakeProvider` function, if one was registered for [type];
         *  3. otherwise, a call to the generated `fakeXxx()` function for [type].
         *
         * Any file backing a case-2 provider is added to [filesDeps] so the generated file
         * correctly depends on it.
         *
         * NOTE: this unifies what used to be two separately-inlined copies of this resolution (one
         * for constructor parameters, one for `@Fake` properties). The property-injection call site
         * ([addFakeInjection]) did not previously unwrap type aliases nor redirect stdlib packages
         * through [fakePackageName] — both are applied uniformly now; the difference is unreachable
         * for any type already covered by [builtins], which is the only stdlib case exercised today.
         */
        private fun fakeInitializerOf(type: KSType, filesDeps: MutableSet<KSFile>): Pair<String, Any> {
            var decl = type.declaration
            while (decl is KSTypeAlias) {
                decl = decl.type.resolve().declaration
            }
            val builtIn = builtins[decl.qualifiedName!!.asString()]
            return when {
                builtIn != null -> builtIn
                type in providedFakes -> {
                    val f = providedFakes[type]!!
                    f.containingFile?.let { filesDeps += it }
                    "%M()" to MemberName(f.packageName.asString(), f.simpleName.asString())
                }
                else -> "%M()" to MemberName(decl.fakePackageName(), "fake${type.toFunName()}")
            }
        }

        /**
         * Appends `return Xxx(param = ...)` to [gFun]: one argument per non-defaulted constructor
         * parameter of [vCls] — `null` for nullable parameters, [fakeInitializerOf] otherwise (a
         * builtin placeholder, a `@FakeProvider`, or a nested `fakeXxx()` call; a no-op lambda when
         * the parameter is itself a function type). Type parameters of [vCls] are substituted using
         * [vType]'s own type arguments.
         */
        private fun addFakeClassConstructorCall(gFun: FunSpec.Builder, vCls: KSClassDeclaration, vType: KSType, filesDeps: MutableSet<KSFile>) {
            val vCstr = vCls.firstPublicConstructor()
                ?: error(vCls, "Could not find public constructor for ${vCls.qualifiedName?.asString()}. Please create a @FakeProvider for it.")
            val args = ArrayList<Pair<String, Any>>()
            vCstr.parameters.forEach { vParam ->
                if (!vParam.hasDefault) {
                    var vParamType = vParam.type.resolve()
                    val vParamTypeDecl = vParamType.declaration
                    if (vParamTypeDecl is KSTypeParameter) {
                        val index = vCls.typeParameters.indexOf(vParamTypeDecl)
                        vParamType = vType.arguments[index].type!!.resolve()
                    }
                    if (vParamType.nullability != Nullability.NOT_NULL) {
                        args.add("${vParam.name!!.asString()} = %L" to "null")
                    } else {
                        val vParamTypeToFake = if (vParamType.isAnyFunctionType) vParamType.arguments.last().type!!.resolve() else vParamType
                        val (template, value) = fakeInitializerOf(vParamTypeToFake, filesDeps)
                        if (vParamType.isAnyFunctionType) {
                            args.add("${vParam.name!!.asString()} = { ${"_, ".repeat(vParamType.arguments.size - 1)}-> $template }" to value)
                        } else {
                            args.add("${vParam.name!!.asString()} = $template" to value)
                        }
                    }
                }
            }
            gFun.addStatement("return %T(${args.joinToString { it.first }})", *(listOf(vCls.toClassName()) + args.map { it.second }).toTypedArray())
        }

        /** Appends `return Xxx.FIRST` to [gFun] — the first declared entry of enum [vCls]. */
        private fun addFakeFirstEnumEntry(gFun: FunSpec.Builder, vCls: KSClassDeclaration) {
            val firstEntry = vCls.declarations.filterIsInstance<KSClassDeclaration>().firstOrNull { it.classKind == ClassKind.ENUM_ENTRY }
                ?: error(vCls, "Cannot fake empty enum class ${vCls.qualifiedName!!.asString()}")
            gFun.addStatement("return %T.%L", vCls.toClassName(), firstEntry.simpleName.asString())
        }

        /**
         * Generates the top-level `fakeXxx(): Xxx` function for [vType], into its own file — a
         * class fake constructs the type via [addFakeClassConstructorCall], an enum fake returns
         * its first entry via [addFakeFirstEnumEntry]:
         *
         * ```
         * internal fun fakeFoo(): Foo = Foo(bar = "")
         * internal fun fakeDirection(): Direction = Direction.NORTH
         * ```
         *
         * Records the generated function name into [fakes], consumed by [generateFakeAccessor].
         */
        private fun generateFakeFunction(vType: KSType, process: ToProcess) {
            val vCls = vType.declaration as KSClassDeclaration
            val filesDeps = HashSet(process.files)
            val mockFunName = "fake${vType.toFunName()}"
            val mockPkg = vCls.fakePackageName()
            val gFile = FileSpec.builder(mockPkg, mockFunName)
            val gFun = FunSpec.builder(mockFunName)
                .addModifiers(visibilityModifier)
                .returns(vType.toTypeName(vCls.typeParameters.toTypeParameterResolver()))
            when (vCls.classKind) {
                ClassKind.CLASS -> addFakeClassConstructorCall(gFun, vCls, vType, filesDeps)
                ClassKind.ENUM_CLASS -> addFakeFirstEnumEntry(gFun, vCls)
                else -> error(vCls, "Cannot process ${vCls.classKind}")
            }
            gFile.addFunction(gFun.build().also { fakes[vType] = MemberName(mockPkg, mockFunName) })
            gFile.build().writeTo(codeGenerator, Dependencies(true, *filesDeps.toTypedArray()))
        }

        // endregion

        // region Phase 5: injectors

        /**
         * Appends the `@Mock` assignment for [vProp] to [gFun]: a `mockFunctionN(...)` call when
         * [vPropType] is itself a function type (a mocked callback property), or `MockXxx(this)`
         * otherwise.
         */
        private fun addMockInjection(gFun: FunSpec.Builder, vProp: KSPropertyDeclaration, vPropType: KSType) {
            val vPropTypeDecl = vPropType.declaration
            if (vPropType.isFunctionType) {
                val argCount = vPropType.arguments.size - 1
                val args =
                    if (argCount == 0) ""
                    else vPropType.arguments.take(argCount).joinToString(prefix = ", ") { "\"${it.type!!.resolve().declaration.qualifiedName!!.asString()}\"" }
                gFun.addStatement(
                    "receiver.%N = %M(this$args)",
                    vProp.simpleName.asString(),
                    MemberName("org.kodein.mock", "mockFunction$argCount"),
                )
            } else {
                gFun.addStatement(
                    "receiver.%N = %T(this)",
                    vProp.simpleName.asString(),
                    ClassName(vPropTypeDecl.packageName.asString(), vPropTypeDecl.toMockName()),
                )
            }
        }

        /** Appends the `@Fake` assignment for [vProp] to [gFun], via [fakeInitializerOf]. */
        private fun addFakeInjection(gFun: FunSpec.Builder, vProp: KSPropertyDeclaration, vPropType: KSType, filesDeps: MutableSet<KSFile>) {
            val (template, value) = fakeInitializerOf(vPropType, filesDeps)
            gFun.addStatement("receiver.%N = $template", vProp.simpleName.asString(), value)
        }

        /**
         * Generates `Mocker.injectMocks(receiver: Xxx)` for class [vCls], setting every
         * `@Mock`/`@Fake` annotated property in [vProps]:
         *
         * ```
         * internal fun Mocker.injectMocks(receiver: SomeTests) {
         *     receiver.foo = MockFoo(this)
         *     receiver.bar = fakeBar()
         * }
         * ```
         */
        private fun generateInjector(vCls: KSClassDeclaration, vProps: List<Pair<String, KSPropertyDeclaration>>) {
            val filesDeps = HashSet<KSFile>().apply { vCls.containingFile?.let { add(it) } }

            val gFile = FileSpec.builder(vCls.packageName.asString(), "${vCls.simpleName.asString()}_injectMocks")
            val gFun = FunSpec.builder("injectMocks")
                .addModifiers(visibilityModifier)
                .receiver(mockerTypeName)
                .addParameter("receiver", vCls.toClassName())
            vProps.forEach { (anno, vProp) ->
                val vPropType = vProp.type.resolve()
                when (anno) {
                    ANNOTATION_MOCK -> addMockInjection(gFun, vProp, vPropType)
                    ANNOTATION_FAKE -> addFakeInjection(gFun, vProp, vPropType, filesDeps)
                }
            }
            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true, *filesDeps.toTypedArray()))
        }

        // endregion

        // region Phase 6: accessors

        /**
         * A [FunSpec.Builder] for accessor function [name], with [visibilityModifier] applied and,
         * in multiplatform projects, `actual` — matching the `expect` declaration generated by the
         * MocKMP Gradle plugin (see `mockmp-gradle-plugin/src/main/resources/mockmp.multi.kt`).
         */
        private fun accessorFunBuilder(name: String): FunSpec.Builder {
            val gFun = FunSpec.builder(name).addModifiers(visibilityModifier)
            if (multiplatform) gFun.addModifiers(KModifier.ACTUAL)
            return gFun
        }

        /**
         * Generates the `Mocker.mock(KClass<T>): T` dispatcher, with one `when` branch per mocked
         * interface:
         *
         * ```
         * internal actual fun <T : Any> Mocker.mock(type: KClass<T>): T = when (type) {
         *     Foo::class -> MockFoo(this) as T
         *     else -> error("Could not find mock for type $type")
         * }
         * ```
         */
        private fun generateMockAccessor() {
            @Suppress("LocalVariableName")
            val T = TypeVariableName("T", Any::class)
            val gFile = FileSpec.builder(accessorsPackage, "mocks")
            val gFun = accessorFunBuilder("mock")
                .receiver(mockerTypeName)
                .addParameter("type", KClass::class.asTypeName().parameterizedBy(T))
                .addTypeVariable(T)
                .returns(T)

            if (mocks.isNotEmpty()) {
                gFun.addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build())
                gFun.beginControlFlow("return when (type)")
                mocks.forEach { (itf, mock) ->
                    val mockTypeName: TypeName =
                        if (itf.typeParameters.isNotEmpty()) {
                            mock.parameterizedBy(*itf.typeParameters.map { it.bounds.first().resolve().toTypeName() }.toTypedArray())
                        } else {
                            mock
                        }
                    gFun.addStatement("%T::class -> %T(this) as T", itf.toClassName(), mockTypeName)
                }
                gFun.addStatement("else -> error(\"Could not find mock for type \$type\")")
                gFun.endControlFlow()
            } else {
                gFun.addStatement("error(\"No mocks declared\")")
            }

            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        /**
         * Generates the `fake(KType): T` dispatcher, with one `when` branch per faked type, keyed
         * by a generated `private val type_Xxx: KType = typeOf<Xxx>()` (faked types can be generic,
         * and `KType` equality — unlike [KClass] — accounts for type arguments):
         *
         * ```
         * private val type_Foo: KType = typeOf<Foo>()
         * internal actual fun <T : Any> fake(type: KType): T = when (type) {
         *     type_Foo -> fakeFoo() as T
         *     else -> error("Could not find fake for type $type")
         * }
         * ```
         */
        private fun generateFakeAccessor() {
            @Suppress("LocalVariableName")
            val T = TypeVariableName("T", Any::class)
            val gFile = FileSpec.builder(accessorsPackage, "fakes")
            fakes.forEach { (type, _) ->
                gFile.addProperty(
                    PropertySpec.builder("type_${type.toFunName()}", KType::class)
                        .addModifiers(KModifier.PRIVATE)
                        .initializer("%M<%T>()", MemberName("kotlin.reflect", "typeOf"), type.toTypeName())
                        .build()
                )
            }
            val gFun = accessorFunBuilder("fake")
                .addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build())
                .addParameter("type", KType::class.asTypeName())
                .addTypeVariable(T)
                .returns(T)

            if (fakes.isNotEmpty()) {
                gFun.beginControlFlow("return when (type)")
                fakes.forEach { (type, fake) -> gFun.addStatement("type_${type.toFunName()} -> %M() as T", fake) }
                gFun.addStatement("else -> error(\"Could not find fake for type \$type\")")
                gFun.endControlFlow()
            } else {
                gFun.addStatement("error(\"No fakes declared\")")
            }
            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        /**
         * Generates the `Mocker.injectMocks(receiver: Any)` dispatcher, with one `when` branch per
         * class that has injected properties:
         *
         * ```
         * internal actual fun Mocker.injectMocks(receiver: Any) = when (receiver) {
         *     is SomeTests -> injectMocks(receiver)
         *     else -> error("Could not find injector for $receiver")
         * }
         * ```
         */
        private fun generateInjectorAccessor() {
            val gFile = FileSpec.builder(accessorsPackage, "injectors")
            val gFun = accessorFunBuilder("injectMocks")
                .receiver(mockerTypeName)
                .addParameter("receiver", Any::class)

            if (toInject.isNotEmpty()) {
                gFun.beginControlFlow("return when (receiver)")
                toInject.forEach { (cls, _) -> gFun.addStatement("is %T -> %M(receiver)", cls.toClassName(), MemberName(cls.packageName.asString(), "injectMocks")) }
                gFun.addStatement("else -> error(\"Could not find injector for \$receiver\")")
                gFun.endControlFlow()
            } else {
                gFun.addStatement("error(\"No injectors declared\")")
            }
            gFile.addFunction(gFun.build())
            gFile.build().writeTo(codeGenerator, Dependencies(true))
        }

        // endregion
    }
}
