{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.micromock",
    "module": "micro-mock-processor",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-processor-0.2.0.jar",
          "url": "micro-mock-processor-0.2.0.jar",
          "size": 29538,
          "sha512": "608f477f636f2dac6a00f47ad96282554520db0b00c82afa7e1685a8e6545297e6fe139cacac09e878366709d49d9dd7ef79b76a7eb5046bcdc09b0901c105d4",
          "sha256": "7d6b88a551dbb1ad816fcfeb4950a7c8630234bd55bc6af41d0063583df51ee3",
          "sha1": "e7b4c49da4093722316b6d5d0eb22eeb093b742e",
          "md5": "63990fe487f0d08c2fe2e4563e13be0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.31-1.0.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-processor-0.2.0.jar",
          "url": "micro-mock-processor-0.2.0.jar",
          "size": 29538,
          "sha512": "608f477f636f2dac6a00f47ad96282554520db0b00c82afa7e1685a8e6545297e6fe139cacac09e878366709d49d9dd7ef79b76a7eb5046bcdc09b0901c105d4",
          "sha256": "7d6b88a551dbb1ad816fcfeb4950a7c8630234bd55bc6af41d0063583df51ee3",
          "sha1": "e7b4c49da4093722316b6d5d0eb22eeb093b742e",
          "md5": "63990fe487f0d08c2fe2e4563e13be0b"
        }
      ]
    }
  ]
}
