{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-metadata-0.5.0-all.jar",
          "url": "micro-mock-0.5.0-all.jar",
          "size": 5827,
          "sha512": "226785b2c758ad1b36ea2055e0a3bec02d15cafcc50def5b52eeba0d35961e0998f7045df47098edca813472f76f8e18f3af363df431bd5a91a949577f3f8567",
          "sha256": "b7ac7b93edc20a34e4d4462da14ce2de822c8620f41dd288fbeb1b27ee5d9f37",
          "sha1": "03bac4834b56cc87bd2e0e69c789b8e0d531ca11",
          "md5": "5e3173faa002592db57cad9d65f78ade"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-0.5.0.jar",
          "url": "micro-mock-0.5.0.jar",
          "size": 5956,
          "sha512": "60e1fdd7f3e224edc597daa04c4325231957fe102bded36febef8a636a2e86be3345dbd0e7d4388cf720d2abc52a598715a16d701b4833eddc4d4654e5c73883",
          "sha256": "8ee268e0959c48a633936afabc725c4898136174f447ae5792b7180d1a80ca9f",
          "sha1": "bbf547f37a594979b5f97808503f63dad8da63c3",
          "md5": "e2bfffa6ca2bc8e9184dfeae6e933ab9"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosarm64/0.5.0/micro-mock-iosarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosarm64/0.5.0/micro-mock-iosarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iossimulatorarm64/0.5.0/micro-mock-iossimulatorarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iossimulatorarm64/0.5.0/micro-mock-iossimulatorarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosx64/0.5.0/micro-mock-iosx64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosx64/0.5.0/micro-mock-iosx64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.5.0/micro-mock-js-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.5.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.5.0/micro-mock-js-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.5.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.5.0/micro-mock-js-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.5.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.5.0/micro-mock-js-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.5.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../micro-mock-jvm/0.5.0/micro-mock-jvm-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-jvm",
        "version": "0.5.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../micro-mock-jvm/0.5.0/micro-mock-jvm-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-jvm",
        "version": "0.5.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosarm64/0.5.0/micro-mock-tvosarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosarm64/0.5.0/micro-mock-tvosarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosx64/0.5.0/micro-mock-tvosx64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosx64/0.5.0/micro-mock-tvosx64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm32/0.5.0/micro-mock-watchosarm32-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm32",
        "version": "0.5.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm32/0.5.0/micro-mock-watchosarm32-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm32",
        "version": "0.5.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm64/0.5.0/micro-mock-watchosarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm64/0.5.0/micro-mock-watchosarm64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosx64/0.5.0/micro-mock-watchosx64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosx64/0.5.0/micro-mock-watchosx64-0.5.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosx64",
        "version": "0.5.0"
      }
    }
  ]
}
