{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.7.0/micro-mock-test-helper-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-iosarm64-0.7.0.klib",
          "size": 9254,
          "sha512": "de3f93610e6d7bc0229ac5f1c9fad6496d4f4755bf1001b1b3fabb7b39824ebc1ee249f96706d98f2bfc8a8b8a790ec62b705384994823e9dc7be8a7f7e3e6cc",
          "sha256": "0bd3bb1344ad5796f30d7b7f2bb4a8cfb1f3f826d56a5601ef863fdad36b3d5c",
          "sha1": "a014247c1e72841eb4f4d4bea4bf57602c43ca6d",
          "md5": "668a0ebd594046ac4be1194cb32cbc2e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-iosarm64-0.7.0-metadata.jar",
          "url": "micro-mock-test-helper-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "9a8c9450b877a17176380a2ed8a09bac2854c6ef26c0de787bf082d553b80db30e2ac195ff21752f6defc6bc3781e9f03f6dd8f93b6fb2aaad2088ba30d7d669",
          "sha256": "a107fa0a33e8398eac3a94d1c162577af25db4f880fdc7b0bc836f33c8376c8c",
          "sha1": "db1b4dfd1d12fb0cfbae387d9b3cbbedb614ef28",
          "md5": "b8e4503cbd77d29134e84ad38cbdb36a"
        }
      ]
    }
  ]
}
