= MocKMP
:toc: preamble
:toclevels: 3
:icons: font
:version: 1.0.0
:ksp-version: 1.6.0-1.0.2

A Kotlin/Multiplatform Kotlin Symbol Processor that generates Mocks & Fakes.

Limitations:

- Mocking only applies to *interfaces*
- Faking only applies to *concrete trees*

Here's a simple overview example:

[source,kotlin]
----
class MyTest : TestsWithMocks() {
    override fun setUpMocks() = injectMocks(mocker)

    @Mock lateinit var view: View
    @Fake lateinit var model: Model
    
    val controller by withMocks { Controller(view = view, firstModel = model) }

    @Test fun controllerTest() {
        every { view.render(isAny()) } returns true
        controller.start()
        verify { view.render(model) }
    }
}
----

Built in collaboration with https://www.deezer.com/[Deezer].


== Usage

=== Mocks

CAUTION: Only *interfaces* can be mocked!


==== Requesting generation

You can declare that a class needs a specific mocked interface by using the `@UsesMocks` annotation.

[source,kotlin]
----
@UsesMocks(Database::class, API::class)
class MyTests {
}
----

Once a type appears in `@UsesMocks`, the processor will generate a mock class for it.


==== Defining behaviour

To manipulate a mocked type, you need a `Mocker`.
You can then create mocked types and define their behaviour:

[source,kotlin]
----
@UsesMocks(Database::class, API::class)
class MyTests {
    @Test fun myUnitTest() {
        val mocker = Mocker()
        val db = MockDatabase(mocker)
        val api = MockAPI(mocker)

        mocker.every { db.open(isAny()) } returns Unit //<1>
        mocker.every { api.getCurrentUser() } runs { fakeUser() } //<2>
    }
}
----
<1> `returns` mocks the method to return the provided *instance*.
<2> `runs` mocks the method to run and return the result of the provided *function*.

Note that a method *must* be mocked to run without throwing an exception (there is no "relaxed" mode).

You can mock methods according to specific argument constraints:

[source,kotlin]
----
mocker.every { api.update(isNotNull()) } returns true
mocker.every { api.update(isNull()) } runs { nullCounter++ ; false }
----

Available constraints are:

- `isAny` is always valid (even with `null` values).
- `isNull` and `isNotNull` check nullability.
- `isEqual` and `isNotEqual` check regular equality.
- `isSame` and `isNotSame` check identity.

Note that passing a non-constraint value to the function is equivalent to passing `isEqual(value)`

[source,kotlin]
----
mocker.every { api.getUserById(42) } returns fakeUser()
----

is strictly equivalent to:

[source,kotlin]
----
mocker.every { api.getUserById(isEqual(42)) } returns fakeUser()
----

WARNING: You cannot mix constraints & non-constraint values.

You can also keep the `Every` reference to change the behaviour over time:

[source,kotlin]
----
val everyApiGetUserById42 = mocker.every { api.getUserById(42) }
everyApiGetUserById42 returns fakeUser()
// Do things...
everyApiGetUserById42 returns null
// Do other things...
----


==== Verification

You can check that mock functions has been run in order with `verify`.

[source,kotlin]
----
val fakeUser = fakeUser()

mocker.every { db.loadUser(isAny()) } returns null
mocker.every { db.saveUser(isAny()) } returns Unit
mocker.every { api.getUserById(isAny()) } returns fakeUser

controller.onClickUser(userId = 42)

mocker.verify {
    db.loadUser(42)
    api.getUserById(42)
    db.saveUser(fakeUser)
}
----

You can of course use constraints (in fact, not using passing a constraint is equivalent to passing `isEqual(value)`):

[source,kotlin]
----
mocker.verify {
    api.getUserById(isAny())
    db.saveUser(isNotNull())
}
----

[WARNING]
====
You cannot mix constraints & non-constraint values.
This fails:

[source,kotlin]
----
mocker.verify {
    api.registerCallback(42, isAny())
}
----

...and needs to be replaced by:

[source,kotlin]
----
mocker.verify {
    api.registerCallback(isEqual(42), isAny())
}
----
====

By default, the `verify` block is exhaustive and in order: it must list *all* mocked functions that were called, *in order*.
This means that you can easily check that no mocked methods were run:

[source,kotlin]
----
mocker.verify {}
----

You can use `clearCalls` to clear the call log, in order to only verify for future method calls:

[source,kotlin]
----
controller.onClickUser(userId = 42)
mocker.clearCalls() //<1>

controller.onClickDelete()
mocker.verify { db.deleteUser(42) }
----
<1> All mocked calls before this won't be verified.

You can verify with:

- `exhaustive = false`, which will verify each call, *in their relative order*, but won't fail if you didn't mention every calls.
- `inOrder = false`, which allows you to define all calls in any order, but will fail if you did not mention all of them.
- `exhaustive = false, inOrder = false`, which checks required calls without order nor exhaustiveness.

[source,kotlin]
----
mocker.verify(exhaustive = false, inOrder = false) { //<1>
    db.deleteUser(42)
    api.deleteUser(42)
}
----
<1> Verify that both calls have been made, no matter the order.
    Other calls to mocks may have been made since exhaustiveness is not checked.


==== Functional types

You can create mocks for functional type by using `mockFunctionX` where X is the number of arguments.

[source,kotlin]
----
val callback: (User) -> Unit = mockFunction1()
mocker.every { callback(isAny()) } returns Unit

userRepository.fetchUser(callback)

mocker.verify { callback(fakeUser) }
----

The `mockFunctionX` builders can accept a lambda parameter that defines behaviour & return type of the mocked function (so that you don't have to call `mocker.every`).
The above mocked callback function can be declared as such:

[source,kotlin]
----
val callback: (User) -> Unit = mockFunction1() {} // implicit Unit
----


==== Accessing arguments

===== Captures

You can capture an argument into a `MutableList` to use or verify it later.
This can be useful, for example, to capture delegates and call them.

[source,kotlin]
----
val delegate = MockDelegate()
mocker.every { delegate.setSession(isAny()) } returns Unit

val controller = Controller(delegate)
controller.startNewSession()
assertEquals(1, controller.runningSessions.size)

val sessionCapture = ArrayList<Session>()
mocker.verify { delegate.setSession(isAny(capture = sessionCapture)) } //<1>

val session = sessionCapture.single() //<2>
session.close()

assertEquals(0, controller.runningSessions.size)
----
<1> Captures the `setSession` first argument into the `sessionCapture` mutable list.
<2> As `setSession` should have been called only once, retrieve the one and only `Session` from the capture list.

Captures can also be used in definition blocks.
The previous example could be rewritten as such:

[source,kotlin]
----
val delegate = MockDelegate()
val sessionCapture = ArrayList<Session>()
mocker.every { delegate.setSession(isAny(capture = sessionCapture)) } returns Unit

val controller = Controller(delegate)
controller.startNewSession()
assertEquals(1, controller.runningSessions.size)

val session = sessionCapture.single()
session.close()

assertEquals(0, controller.runningSessions.size)
----

Note that, when declared in a definition block, the capture list may be filled with multiple values (one per call).


===== Run block

You can access function parameters from a run block.
This is less precise than using caputre lists as they are non typed, but allows to write very concise code:

[source,kotlin]
----
val delegate = MockDelegate()
mocker.every { delegate.setSession(isAny()) } runs { args ->
    (args[0] as Session).close()
}

val controller = Controller(delegate)
controller.startNewSession()

assertEquals(0, controller.runningSessions.size)
----


==== Custom constraints

You can define your own constraints:

[source,kotlin]
----
fun ArgConstraintsBuilder.isStrictlyPositive(capture: MutableList<Int>? = null): Int =
    isValid(ArgConstraint(capture, "isStrictlyPositive") {
        if (it >= 0) ArgConstraint.Result.Success
        else ArgConstraint.Result.Failure { "Expected a strictly positive value, got $it" }
    })
----

...and use them in *definition*:

[source,kotlin]
----
mocker.every { api.getSuccess(isStrictlyPositive()) } returns true
mocker.every { api.getSuccess(isAny()) } returns false
----

...or in *verification*:

[source,kotlin]
----
mocker.verify { api.getUserById(isStrictlyPositive()) }
----


=== Fakes

CAUTION: Only *concrete trees* (concrete classes containing concrete classes) can be faked!.

*Data classes* are ideal candidates for faking.


==== Requesting generation

You can declare that a class needs a specific faked data by using the `@UsesFakes` annotation.

[source,kotlin]
----
@UsesFakes(User::class)
class MyTests {
}
----

Once a type appears in `@UsesFakes`, the processor will generate a fake function for it.


==== Instantiating

Once a class has been faked, you can get a new instance by calling its `fake*` corresponding function:

[source,kotlin]
----
@UsesFakes(User::class)
class MyTests {
    val user = fakeUser()
}
----

Here are the rules the processor uses to generate fakes:

* Nullable values are always `null`.
* `Boolean` values are set to `false`.
* Numeric values are set to `0`.
* `String` values are set to empty `""`.
* Other non-nullable non-primitive values are faked.

[TIP]
====
By using a `data class`, you can easily tweak your fakes according to your needs:

[source,kotlin]
----
val user = fakeUser().copy(id = 42)
----
====


=== Injecting your tests

Instead of creating your own mocks & fakes, it can be useful to inject them in your test class, especially if you have multiple tests using them.

[source,kotlin]
----
@UsesFakes(User::class)
class MyTests {
    @Mock lateinit var db: Database
    @Mock lateinit var api: API

    @Fake lateinit var user: User

    lateinit var controller: Controller

    val mocker = Mocker()

    @BeforeTest fun setUp() {
        mocker.reset() //<1>
        this.injectMocks(mocker) //<2>
        controller = ControllerImpl(db, api) //<3>
    }

    @Test fun controllerTest() {
        mocker.every { view.render(isAny()) } returns true
        controller.start()
        mocker.verify { view.render(model) }
    }
}
----
<1> Resets the mocker before any test (which removes all mocked behaviour & logged calls), so that each test gets a "clean" mocker.
<2> Injects mocks and fakes.
<3> Create classes to be tested with injected mocks & fakes.

As soon as a class `T` contains a `@Mock` or `@Fake` annotated property, a `T.injectMocks(Mocker)` function will be created by the processor.

IMPORTANT: Don't forget to `reset` the `Mocker` in a `@BeforeTest` method!


=== Test class helper

MocKMP provides the `TestsWithMocks` helper class that your test classes can inherit from.
It provides the following benefits:

- Provides a `Mocker`.
- Resets the `Mocker` before each tests.
- Provides `withMock` property delegates to initialize objects with mocks.
- Allows to call `every` and `verify` without `mocker.`.

It does not come with the stndard runtime (as it forces the dependency to JUnit on the JVM), so you need to add the `mockmp-test-helper` dependency to use it.

The above `MyTests` sample can be rewritten as such:

[source,kotlin]
----
@UsesFakes(User::class)
class MyTests : TestsWithMocks() { //<1>
    override fun setUpMocks() = injectMocks(mocker) //<2>

    @Mock lateinit var db: Database
    @Mock lateinit var api: API

    @Fake lateinit var user: User

    val controller by withMock { ControllerImpl(db, api) } //<3>

    @Test fun controllerTest() {
        every { view.render(isAny()) } returns true //<4>
        controller.start()
        verify { view.render(model) } //<4>
    }
}
----
<1> The class inherits `TestsWithMocks`, which provides helpers.
<2> `setUpMocks` must be overriden, and can generally be just a delegation to the `injectMocks` generated function.
<3> Controller will be (re)created before each tests with the new mock dependencies.
<4> Note the absence of `mocker.` as you can use `every` and `verify` directly.

NOTE: Properties delegated to `withMocks` will be (re)initialized *before each tests*, after the mocks have been (re)injected.


== Setup

=== With KSP

MocKMP is a Kotlin Symbol Processor, so you need to apply KSP to use it.


=== With the plugin

The MocKMP Gradle plugin configures your project to use the Kotlin Symbol Processor using a workaround to a current KSP limitation (see <<buggy-multiplatform>>).

Once KSP properly supports hierarchical Multiplatform, this plugin will apply MocKMP "normally".

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
plugins {
    kotlin("multiplatform")
    id("org.kodein.mock.mockmp") version "{version}" //<1>
}

repositories {
    mavenCentral()
}

mockmp {
    // OPTIONAL!
    usesHelper = true //<2>
}

kotlin {
    jvm()
    ios()
    js(IR) {
        browser()
    }

    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}
----
<1> Applying the MocKMP plugin.
<2> Requesting the *optional* `test-helper` dependency

The plugin takes care of:

* Applying the KSP Gradle plugin
* Declaring the MocKMP KSP dependency
* Declaring the MocKMP runtime dependencies
* Applying the buggy multiplatform workaround


[[buggy-multiplatform]]
==== Buggy multiplatform

KSP for multiplatform is in beta, and *https://github.com/google/ksp/issues/567[KSP for common tests is not supported]* (yet).

To have IDEA completion, here's a trick that you can use:

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
plugins {
    kotlin("multiplatform")
    id("com.google.devtools.ksp") version "{ksp-version}" //<1>
}

repositories {
    mavenCentral()
}

kotlin {
    jvm()
    ios()
    js(IR) {
        browser()
    }

    sourceSets {
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.kodein.mock:mockmp-runtime:{version}") //<2>
                // OPTIONAL!
                implementation("org.kodein.mock:mockmp-test-helper:{version}") //<2>
            }
            kotlin.srcDir("build/generated/ksp/jvmTest/kotlin") //<3>
        }
    }
}

dependencies {
    "kspJvmTest"("org.kodein.mock:mockmp-processor:{version}") //<4>
}

tasks.withType<org.jetbrains.kotlin.gradle.dsl.KotlinCompile<*>>().all {
    if (name.startsWith("compileTestKotlin")) {
        dependsOn("kspTestKotlinJvm") //<5>
    }
}
----
<1> Applying the KSP plugin.
<2> Adding the dependencies to the MocKMP runtime and the *optional* test helper.
<3> Use KSP generated JVM sources on all targets.
<4> Apply the processor only on the JVM target.
<5> Make compilation of all targets dependant on the JVM KSP processor.
