{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.2.0/micro-mock-0.2.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-iosarm64-0.2.0.klib",
          "size": 30931,
          "sha512": "19457c008b424f91b6c91713c914dbd1de09963a0c3b444d02fcbe2f1894fac2888883b4b7a1b719744c61baf2bbdab3fd32d36fb911c7db912708a1822311ed",
          "sha256": "13aa2e51b1f99ff09e264a669d1a2ab151221dc7b3a7163ffd0c554e4bfa2f1f",
          "sha1": "efde019ed60901dc873c016de89c07fb0e20da0e",
          "md5": "d89835608b047b5315d410dc7de57a1f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-iosarm64-0.2.0-metadata.jar",
          "url": "micro-mock-iosarm64-0.2.0-metadata.jar",
          "size": 4310,
          "sha512": "2f624047e522a183ff1692315838eb256f058800b9f5a024f0a9b4d9b7df2e12996b21830347ae271789503c200855c9c11bd3e9d8bd736cccdee1142f66a946",
          "sha256": "0b5cfd03601981785f1ba0198af0249098b79deba4d71a1ce4e1bff24631aabe",
          "sha1": "d1853dff3e82d0be6539f79b873e94e7bc828b33",
          "md5": "18ead9616f54ac00d3e8cd175c5ccce2"
        }
      ]
    }
  ]
}
