{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.4.0/micro-mock-0.4.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-watchosarm32-0.4.0.klib",
          "size": 33725,
          "sha512": "7f3525744064e904af0dfca2f1ba26057fe15c6f6b94fbb29764f8db0c4b552a18f11e3e248a7233fc18d2528a736b9c2daaa94c6e3139f638c6d03c7cb69db3",
          "sha256": "1fc33bcb2b7d31231147bdd1e6435fbd33b96707f80f66e6ebf4120b971efea2",
          "sha1": "7cf09d3fcd9e20cabeccb76b53301459c3340edc",
          "md5": "9c8aa6a36b2c0907338ca6de98a8a1c0"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-watchosarm32-0.4.0-metadata.jar",
          "url": "micro-mock-watchosarm32-0.4.0-metadata.jar",
          "size": 4310,
          "sha512": "8c8fd76a33d403bb9382055d12f1b5756f3b1c1f8f7629a4ad7689e1eda27bfde39530a2a49ae750c3b017466ac9045ec81acaab4987a003c043cf67714621db",
          "sha256": "06e3d613e61e2e52f461a1d5dbf7b13d32b12d57f79ff5b6e7b0dc5132ca1432",
          "sha1": "ca5f7800f454ccb9cc772df2b29c555bd43cce10",
          "md5": "d41208e767849a0d9a5b9df2d655c9d2"
        }
      ]
    }
  ]
}
