{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.7.0/micro-mock-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-watchosarm32-0.7.0.klib",
          "size": 51636,
          "sha512": "e9ca5fcfee1b8d433ee0a9dd228de9b218b8719f6a7ceb66ffd9b498d0332373dea536139ea132e296ef88758d63775f90a856f83e8dfc85433a096903d49e61",
          "sha256": "bd8ee6b93db32b94642313a4fc95bd1f0690d267bf5a3ccc1f6389f3959ceb77",
          "sha1": "bf5cd396a81cf67dd2091116f57cba1f8a690249",
          "md5": "9c17b0ae199b1bd7c701a72c56f997f7"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-watchosarm32-0.7.0-metadata.jar",
          "url": "micro-mock-watchosarm32-0.7.0-metadata.jar",
          "size": 4713,
          "sha512": "fd189068e358617bc1dcc07d7ba513ad69b1c91019c74146375f5ab6ad16b6cdf3ec6f865e007853c73052c52aa9677a36f32a2a941071e78e82fe135a4c6d41",
          "sha256": "0b62193bcf4d3594d60fc7a0136f475cd0355123da3ea7a72c894a06366abac0",
          "sha1": "549bdfd8b9423869ca584a4a6964516f14baaffa",
          "md5": "db8153f661fb6dbcbfbe7f67c526633a"
        }
      ]
    }
  ]
}
