{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.7.0/micro-mock-test-helper-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-tvosx64-0.7.0.klib",
          "size": 9247,
          "sha512": "a7442306ed3faac4bc8ade5fab3ef17dbcdc9715c39acddca65fcaeebd5fcebbeb4f9838fc155fa8341f9d81ff15f97912b996c03b46f3db91278216988b5225",
          "sha256": "7217e2b9d149fe99e49d5bfd08fa4d04d0857be79431a61d162408ef2bec3522",
          "sha1": "aca7a72d16a027fbe74e208b45e480f68a4fb5ff",
          "md5": "1aeca6f3c1175fbbf1a81eafa8d03ceb"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-tvosx64-0.7.0-metadata.jar",
          "url": "micro-mock-test-helper-tvosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "5ce42ceb47bc8cef96105f467ddac2d8aa9a9b1bddd4e069aa896491d2c1b8327ec7798ecafe594cab649c5349d229d28c4a7d38488c3b0ec493911eb9c9b71a",
          "sha256": "d8a1225f2e13ffb0e5507769739b919adbb0fb332a6d749c78efabed66d70455",
          "sha1": "1f7e476c634d8a8c1b2b8aae4c05df99654182e8",
          "md5": "289017d1fb77d84de21a6aa4ac507f82"
        }
      ]
    }
  ]
}
