{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.6.0/micro-mock-test-helper-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-iossimulatorarm64-0.6.0.klib",
          "size": 9340,
          "sha512": "72bcc7d08df701e1f3d7e9806d88054f82397c69359ab73ad020509cf11c7abbaaff76d2b08f18722a129d4db15fa5c60fab710cb55dde0f0da2a9f724200121",
          "sha256": "6974049aafe3951e1722d8c453b67b2fbecc67c8c0b8d3c98d57df210802a7cc",
          "sha1": "cea5ab365e16b74710906052a1fb94f245d293a9",
          "md5": "40f11bec479a6d42b9c78b149f4516ad"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-iossimulatorarm64-0.6.0-metadata.jar",
          "url": "micro-mock-test-helper-iossimulatorarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "9bcd64cb8a84d3388d56e26ab295b74c8145d1b3dd0af280d7522806215bee19aa00ec93dd847080d20adf9cfead7db25d7af986f5059276b70cf1433f139956",
          "sha256": "35d54fc03980329d5495dccefd0d22531143ac025a2bb81431c1e9129fe72811",
          "sha1": "f12fe1a384e0ffd4f6cc9ae63a183f5c58133c39",
          "md5": "2df5234f07a9ca014823bd31c5c0ada5"
        }
      ]
    }
  ]
}
