{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-metadata-0.3.0-all.jar",
          "url": "micro-mock-0.3.0-all.jar",
          "size": 5694,
          "sha512": "c309e5f28e39a79dc978e86fef787eca5bc2e38a7d863ab026139609c0bdd1bee300d1285f4ba31361098bfb45ab756e04aa87a93b016ea0038c8973060fa19b",
          "sha256": "6016a923c28c7802a556e165ccd73013cb5a067e6b78a11f658e697432511e53",
          "sha1": "5a31ff32ad6a9bd7118983b317c58f1a8ddc9c0a",
          "md5": "b1f2341b53558bf45862262e9d4d7dc3"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-0.3.0.jar",
          "url": "micro-mock-0.3.0.jar",
          "size": 5833,
          "sha512": "fd40dc4a86dfb1c02153d9841029344888a643712a1bd6d236b8010872cf8f64d638fe7e4004a2fd50fd8204595c88aa0d2a47699399deaf3facd2ac81d39966",
          "sha256": "d27919b45e0e9d75579a0cc7bfdcd27854b8180e9a615d31e6ee89669b7bf1c4",
          "sha1": "9a0822340c386b550ebc05a115fb0ee47827486c",
          "md5": "89df8aa64172eb0659f50546275f863d"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosarm64/0.3.0/micro-mock-iosarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosarm64/0.3.0/micro-mock-iosarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iossimulatorarm64/0.3.0/micro-mock-iossimulatorarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iossimulatorarm64/0.3.0/micro-mock-iossimulatorarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iossimulatorarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosx64/0.3.0/micro-mock-iosx64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-iosx64/0.3.0/micro-mock-iosx64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-iosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.3.0/micro-mock-js-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.3.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.3.0/micro-mock-js-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.3.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.3.0/micro-mock-js-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.3.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../micro-mock-js/0.3.0/micro-mock-js-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-js",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../micro-mock-jvm/0.3.0/micro-mock-jvm-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../micro-mock-jvm/0.3.0/micro-mock-jvm-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosarm64/0.3.0/micro-mock-tvosarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosarm64/0.3.0/micro-mock-tvosarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosx64/0.3.0/micro-mock-tvosx64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-tvosx64/0.3.0/micro-mock-tvosx64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-tvosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm32/0.3.0/micro-mock-watchosarm32-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm32",
        "version": "0.3.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm32/0.3.0/micro-mock-watchosarm32-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm32",
        "version": "0.3.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm64/0.3.0/micro-mock-watchosarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosarm64/0.3.0/micro-mock-watchosarm64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosarm64",
        "version": "0.3.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosx64/0.3.0/micro-mock-watchosx64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosx64",
        "version": "0.3.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../micro-mock-watchosx64/0.3.0/micro-mock-watchosx64-0.3.0.module",
        "group": "org.kodein.micromock",
        "module": "micro-mock-watchosx64",
        "version": "0.3.0"
      }
    }
  ]
}
