{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.6.0/micro-mock-test-helper-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-watchosarm32-0.6.0.klib",
          "size": 9289,
          "sha512": "485703c3bb68cfd83987412fb85a0c2b3bab6fd743797d13f53d6af497e4702b237375326e34d6edf48861815891447af4b96cca54f51a4e02b1a6df88076669",
          "sha256": "f52d48882cf138642d649e6e35f41fbb0c5f38fdb1ba2e50e7845c447adf1338",
          "sha1": "2eb03a275319c08658a4e5256471f3efc34f8f5a",
          "md5": "f2a67cbf3c0e86a5b12958b1b7a5ae56"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-watchosarm32-0.6.0-metadata.jar",
          "url": "micro-mock-test-helper-watchosarm32-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "916a9fc686a16cbf3fab5b383c9422653a8eb1f93ea56846c961f19976aca4091aa10ed468cac2e303fe3eb01ef843098e2de61a61c0ae1ff5866fd1a220e551",
          "sha256": "dfb7eccf93052dfda0fc3f749a3c83d42fd86d717cb163d63e8e396a8954ee90",
          "sha1": "8869c495a593a1bf3038341d69242aac458bf1e5",
          "md5": "21b95490ca98c877dbd2c39589fc25ac"
        }
      ]
    }
  ]
}
