{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.7.0/micro-mock-test-helper-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-iosx64-0.7.0.klib",
          "size": 9238,
          "sha512": "f77575f2435316028e268c63b249e5181eb38739a68e2bc4b4e948ef5a6923eacd44452fd0ef5742ee3d926fbf2f9edcc35a73cfc38cb0e66faa1d52ac6f4b53",
          "sha256": "8ef1f57a42e792401394d4642bc13ee454e0368bfc2287f447b8c6ecf457fa20",
          "sha1": "ef3e25414b35469a4222f9c10a8ae58097be1d47",
          "md5": "b1e77847dc3ee615506584c95a845075"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-iosx64-0.7.0-metadata.jar",
          "url": "micro-mock-test-helper-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "6f84dfc3c9f9e5426745206f93300fc83d7f1b1c96369ea4c0a209b2451bda187b8b32b5ddf9c12726180001284bba22a176ab66ff8d5fd4032b9a061c2db768",
          "sha256": "4d2c48be385988f332ae8bc8401ae1240c615d7748adabd843ef2f24b7f45d8b",
          "sha1": "ededa5323bcd4c58b51e29741b975670ae709b11",
          "md5": "f334b265e036dfca252dbd38f6cb28c7"
        }
      ]
    }
  ]
}
