{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.7.0/micro-mock-test-helper-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-jslegacy-0.7.0.jar",
          "url": "micro-mock-test-helper-js-0.7.0.jar",
          "size": 18516,
          "sha512": "447249b5b1126387fb79d9cc33a238e334bb6301c6376549dc66849996f8cd260ff6a16f9daf8038d88727fc411e5f651bd116591b32169798c48c7a55d7f3b3",
          "sha256": "f9aea6ebc9f79f6355bf2ad21b9d95d026da0070ed24f8cfd9e5c5141ad2ceda",
          "sha1": "e7c733ee829d03f2aae8f7fbb2007cb0cb6ef939",
          "md5": "9423fe6d97fdbe8e753e6be8d171c381"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-jslegacy-0.7.0.jar",
          "url": "micro-mock-test-helper-js-0.7.0.jar",
          "size": 18516,
          "sha512": "447249b5b1126387fb79d9cc33a238e334bb6301c6376549dc66849996f8cd260ff6a16f9daf8038d88727fc411e5f651bd116591b32169798c48c7a55d7f3b3",
          "sha256": "f9aea6ebc9f79f6355bf2ad21b9d95d026da0070ed24f8cfd9e5c5141ad2ceda",
          "sha1": "e7c733ee829d03f2aae8f7fbb2007cb0cb6ef939",
          "md5": "9423fe6d97fdbe8e753e6be8d171c381"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-jsir-0.7.0.klib",
          "url": "micro-mock-test-helper-js-0.7.0.klib",
          "size": 6982,
          "sha512": "6ef3f21955cfa80c9f747baedb62285c60fbf6f00285767ac54c70816477acd9592ff3a8f8fa63782a8e7d3ac2e8e66161825fbe1bdc2ade43895b782a516fc7",
          "sha256": "53062ea1c7a8b353e3dbc73f483a86012c416314692e4c88841eefe2412b3eca",
          "sha1": "61425757d973f4b8ca2f5479cc2f78e46058284c",
          "md5": "8e8766faa39e3612bed48324630b96cd"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-jsir-0.7.0.klib",
          "url": "micro-mock-test-helper-js-0.7.0.klib",
          "size": 6982,
          "sha512": "6ef3f21955cfa80c9f747baedb62285c60fbf6f00285767ac54c70816477acd9592ff3a8f8fa63782a8e7d3ac2e8e66161825fbe1bdc2ade43895b782a516fc7",
          "sha256": "53062ea1c7a8b353e3dbc73f483a86012c416314692e4c88841eefe2412b3eca",
          "sha1": "61425757d973f4b8ca2f5479cc2f78e46058284c",
          "md5": "8e8766faa39e3612bed48324630b96cd"
        }
      ]
    }
  ]
}
