{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.6.0/micro-mock-test-helper-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-tvosarm64-0.6.0.klib",
          "size": 9262,
          "sha512": "a5e0161183a5df5df8bda4115b329db1ac98137e76e68d1fd868eef42be826bfccfb9ef7bf8631f4e4981da4d4fc8edcc5bd26a22847bbf0ae758889bc8a11e8",
          "sha256": "04d8a1fb777b56d404bbca4184e718e5e2d85e6babc85168a1ad3e3443072c78",
          "sha1": "72c8ff1c4c752a4873c807e7467af1bd418ff025",
          "md5": "e1823cf6ceaa1c58c1b32b0b2b10a1aa"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-tvosarm64-0.6.0-metadata.jar",
          "url": "micro-mock-test-helper-tvosarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "d8fe4ec7fb8f78770313d1853d838cdcde58cdfc64fd7bc085c4f206ed143c6b6c1c243fac996d975bd17e0ff6443bb333ddd0c8b27d1ced98d6916f4a9c5f08",
          "sha256": "a2d051e894ecdd283a48570f913e382f83de8c79c30559ad7bc9b01e11011021",
          "sha1": "d096f5e1705f51b5a49981c83b1c852842df0044",
          "md5": "cc30d402e8b11a6f1ec5366205a5e3d2"
        }
      ]
    }
  ]
}
