{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.5.0/micro-mock-test-helper-0.5.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-tvosarm64-0.5.0.klib",
          "size": 9262,
          "sha512": "a5e0161183a5df5df8bda4115b329db1ac98137e76e68d1fd868eef42be826bfccfb9ef7bf8631f4e4981da4d4fc8edcc5bd26a22847bbf0ae758889bc8a11e8",
          "sha256": "04d8a1fb777b56d404bbca4184e718e5e2d85e6babc85168a1ad3e3443072c78",
          "sha1": "72c8ff1c4c752a4873c807e7467af1bd418ff025",
          "md5": "e1823cf6ceaa1c58c1b32b0b2b10a1aa"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-tvosarm64-0.5.0-metadata.jar",
          "url": "micro-mock-test-helper-tvosarm64-0.5.0-metadata.jar",
          "size": 261,
          "sha512": "b938eb12794b2e170f7eb2e9bcf5b38fe35fcdeb88b02d51b1c7c2b7936144179c8cc77cef086645c15ff1ccfc50cd8453dd354cf03f1b9e77f4672dd367b7b9",
          "sha256": "215517bef05647b198f219445a753636d5c39bdb523e638479e3420a05019c65",
          "sha1": "edf46d9b109f39663fc556b7dd46c7b186408c61",
          "md5": "6b1cab47918b8bbcf7ca6bc0052a714f"
        }
      ]
    }
  ]
}
