{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.2.0/micro-mock-0.2.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jslegacy-0.2.0.jar",
          "url": "micro-mock-js-0.2.0.jar",
          "size": 71445,
          "sha512": "9f4bee9541cb3e147516d7a640a3a038a0f979342356e6e13f8a36fefae15ade0c7819cd82378d12649312713fdda82504ee2a57d151fc1ec0a8884fbbb5f0f8",
          "sha256": "a3b13b2a7221d700d44885f12b00afedd55a7aae9ad53f618985d555dc2fff08",
          "sha1": "08708ad5359b3b1edeb0b18532d9e395221610ba",
          "md5": "a5094c16b3262fc616c97e1d0c325bc7"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jslegacy-0.2.0.jar",
          "url": "micro-mock-js-0.2.0.jar",
          "size": 71445,
          "sha512": "9f4bee9541cb3e147516d7a640a3a038a0f979342356e6e13f8a36fefae15ade0c7819cd82378d12649312713fdda82504ee2a57d151fc1ec0a8884fbbb5f0f8",
          "sha256": "a3b13b2a7221d700d44885f12b00afedd55a7aae9ad53f618985d555dc2fff08",
          "sha1": "08708ad5359b3b1edeb0b18532d9e395221610ba",
          "md5": "a5094c16b3262fc616c97e1d0c325bc7"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jsir-0.2.0.klib",
          "url": "micro-mock-js-0.2.0.klib",
          "size": 26980,
          "sha512": "2416a878134f845d8973f9496d078a353ce01ea854d6aa51db58f3ee544b0f4da80e952ed24eced15d35f5e367cbf39d2f8048d3fb0b24baedddb5c62a0f69aa",
          "sha256": "b95235b3c1bb79d52c0a7979c9b0930d0f015ce11671e71b4d18550af575df16",
          "sha1": "87846d3fe10ff7dad66c2f4f6a4e6826efb00125",
          "md5": "f9501f3c4a44fe9c6e3f60f6ff1da198"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jsir-0.2.0.klib",
          "url": "micro-mock-js-0.2.0.klib",
          "size": 26980,
          "sha512": "2416a878134f845d8973f9496d078a353ce01ea854d6aa51db58f3ee544b0f4da80e952ed24eced15d35f5e367cbf39d2f8048d3fb0b24baedddb5c62a0f69aa",
          "sha256": "b95235b3c1bb79d52c0a7979c9b0930d0f015ce11671e71b4d18550af575df16",
          "sha1": "87846d3fe10ff7dad66c2f4f6a4e6826efb00125",
          "md5": "f9501f3c4a44fe9c6e3f60f6ff1da198"
        }
      ]
    }
  ]
}
