{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.2.0/micro-mock-0.2.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jslegacy-0.2.0.jar",
          "url": "micro-mock-js-0.2.0.jar",
          "size": 71445,
          "sha512": "1d70d8b972987270c6c8a0f5649ee7588e57f1d5197e2d0907d73cca3dc6ba4d8ce8bffc35d0a18dbbdb1ccbd3bb9c457085cbb11dd0a48d7ed64cbe0601d787",
          "sha256": "e83435a4fe13ccf2831d533880fe2304bca30618bc2dd0d493cefae6f162a759",
          "sha1": "29577af0d39b7654d907a0d835a5cca50499bfea",
          "md5": "e3856697d93ad563473bb9038647142b"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jslegacy-0.2.0.jar",
          "url": "micro-mock-js-0.2.0.jar",
          "size": 71445,
          "sha512": "1d70d8b972987270c6c8a0f5649ee7588e57f1d5197e2d0907d73cca3dc6ba4d8ce8bffc35d0a18dbbdb1ccbd3bb9c457085cbb11dd0a48d7ed64cbe0601d787",
          "sha256": "e83435a4fe13ccf2831d533880fe2304bca30618bc2dd0d493cefae6f162a759",
          "sha1": "29577af0d39b7654d907a0d835a5cca50499bfea",
          "md5": "e3856697d93ad563473bb9038647142b"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jsir-0.2.0.klib",
          "url": "micro-mock-js-0.2.0.klib",
          "size": 26979,
          "sha512": "1c5da479ac6610419fe2a7ed02ce4c5f2a418351ead9daf5367d5666c03d1825b6300ec72d85fa0cbcbc2dd42a19fe1a231ac5a6e2b26ad628b0e5679d68ae98",
          "sha256": "f9e1e031df09a21a84efd7b426e1443805b1a25df304779942b9e7cd5851fa2b",
          "sha1": "aeea2379fa0349b6780762e138eb25a0d846aa27",
          "md5": "4044f0542856d43356e232e95acb08a9"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jsir-0.2.0.klib",
          "url": "micro-mock-js-0.2.0.klib",
          "size": 26979,
          "sha512": "1c5da479ac6610419fe2a7ed02ce4c5f2a418351ead9daf5367d5666c03d1825b6300ec72d85fa0cbcbc2dd42a19fe1a231ac5a6e2b26ad628b0e5679d68ae98",
          "sha256": "f9e1e031df09a21a84efd7b426e1443805b1a25df304779942b9e7cd5851fa2b",
          "sha1": "aeea2379fa0349b6780762e138eb25a0d846aa27",
          "md5": "4044f0542856d43356e232e95acb08a9"
        }
      ]
    }
  ]
}
