{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.6.0/micro-mock-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-watchosx64-0.6.0.klib",
          "size": 51620,
          "sha512": "9798e66925dcaa4145c5a7cd0e07d7b37cdcbf7a79e1f978949086308f23d630e9a758ea4a5f6678cbe13cc853bcf05c0a99509c62eedf620b1e1dc5c4b16ef5",
          "sha256": "da91d02ee05524395b38760e183c1392cedcf49a6c62ac0ea78af214a848d998",
          "sha1": "63bf6931e660329ce20cd538a5330bcf5565e0da",
          "md5": "a03117d78ef69d03c18598f2a5634224"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-watchosx64-0.6.0-metadata.jar",
          "url": "micro-mock-watchosx64-0.6.0-metadata.jar",
          "size": 4713,
          "sha512": "23bbf2edc28ebc68896233babf58e371074d8a8dcf530b893f20b4f9c99a5241ac693babaf5289accf20f25555492a2170692b544fde4b657fbefc445f2b6426",
          "sha256": "5394500a3033a29584fe11a15e4e173585d73a75b18f0f191ef57b78a0ca2178",
          "sha1": "ac88155ab29a8aa352b6e2cecfde92a0bb49082d",
          "md5": "e38a7217cb2f8d639a1408cb852c453d"
        }
      ]
    }
  ]
}
