{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.4.0/micro-mock-0.4.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-iosx64-0.4.0.klib",
          "size": 33674,
          "sha512": "fbb72595baa2253707f590bf0f6af4c7cdcf327a5bf1c151a6e6d2746b9d31452a5c6f1f72cfa891bd8399896b51b021e89a41a6f37bc0d61934c606425928f4",
          "sha256": "6a4baa4d10b9af9ca7ca6bb76ee4e3c8fe78c06bbe07c80c339633b518621c66",
          "sha1": "eaf260bd5bd945654e9c541ca84c79eda4e77fc7",
          "md5": "3da204190b805b858353d4f8f56ac332"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-iosx64-0.4.0-metadata.jar",
          "url": "micro-mock-iosx64-0.4.0-metadata.jar",
          "size": 4310,
          "sha512": "e000ba4748f25e4512da5078a5f0e280ef7863665061a958322e0b3685110ba832abbb9bb1746432a33c73f51afd86f80f6f2ce3f9b76598a35bcbf4f7a11226",
          "sha256": "1e6713482dca12233ef391e650ea8f847682230a8a40c6f16abac5cdc2f98e59",
          "sha1": "74b735fafce2a06336e917aec7af81b2eaeeb419",
          "md5": "aaffae4f37fff3f54aece914e3cc4293"
        }
      ]
    }
  ]
}
