{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.6.0/micro-mock-test-helper-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-tvosx64-0.6.0.klib",
          "size": 9247,
          "sha512": "a7442306ed3faac4bc8ade5fab3ef17dbcdc9715c39acddca65fcaeebd5fcebbeb4f9838fc155fa8341f9d81ff15f97912b996c03b46f3db91278216988b5225",
          "sha256": "7217e2b9d149fe99e49d5bfd08fa4d04d0857be79431a61d162408ef2bec3522",
          "sha1": "aca7a72d16a027fbe74e208b45e480f68a4fb5ff",
          "md5": "1aeca6f3c1175fbbf1a81eafa8d03ceb"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-tvosx64-0.6.0-metadata.jar",
          "url": "micro-mock-test-helper-tvosx64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "916a9fc686a16cbf3fab5b383c9422653a8eb1f93ea56846c961f19976aca4091aa10ed468cac2e303fe3eb01ef843098e2de61a61c0ae1ff5866fd1a220e551",
          "sha256": "dfb7eccf93052dfda0fc3f749a3c83d42fd86d717cb163d63e8e396a8954ee90",
          "sha1": "8869c495a593a1bf3038341d69242aac458bf1e5",
          "md5": "21b95490ca98c877dbd2c39589fc25ac"
        }
      ]
    }
  ]
}
