{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.4.0/micro-mock-0.4.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-tvosarm64-0.4.0.klib",
          "size": 33699,
          "sha512": "2ef27b45ff367d18e0d4dfa0261248b938fda68da659689b42416b2be17bc1ebb4e8443b9914ec6e39a5288cbb2077ac5bbf6e430908e1cc3985a3b491443053",
          "sha256": "7959e61ee48dfacef770e4a89f467e2184cdd97154ed1661dade197558043009",
          "sha1": "ddf6be1a4757fc149f7dd5de64417924cfd7511e",
          "md5": "cf27019a7bc0e8108e173562cdbbe6f0"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-tvosarm64-0.4.0-metadata.jar",
          "url": "micro-mock-tvosarm64-0.4.0-metadata.jar",
          "size": 4310,
          "sha512": "57207680586cabd660326f2dcf930df623446fbfb3972114a12a1216a6a796c1ca5d40439e148f555c20559bd56355851b43172073a4f6ed709c20c28de14896",
          "sha256": "8a39fb40407f73ed30a373c21df220f6220cfeb9d13c52833115d0dc3c4f3224",
          "sha1": "38a1efd36af0a07fc6e4e0a33d2e59ab740d6b4c",
          "md5": "b1b6aaabd104ef559a99a0ed1dbca005"
        }
      ]
    }
  ]
}
