{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.7.0/micro-mock-test-helper-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-iossimulatorarm64-0.7.0.klib",
          "size": 9340,
          "sha512": "72bcc7d08df701e1f3d7e9806d88054f82397c69359ab73ad020509cf11c7abbaaff76d2b08f18722a129d4db15fa5c60fab710cb55dde0f0da2a9f724200121",
          "sha256": "6974049aafe3951e1722d8c453b67b2fbecc67c8c0b8d3c98d57df210802a7cc",
          "sha1": "cea5ab365e16b74710906052a1fb94f245d293a9",
          "md5": "40f11bec479a6d42b9c78b149f4516ad"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "micro-mock-test-helper-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "34846e651996c3a63a9fc3d72e1eee31b324b3455f2fd5c3b2daf64703d85f71e8760b645f039f3138c052be40a8a4bb70715028e8414abc17dec0a2f7501b0f",
          "sha256": "716fbe96051b9a6b389f79ef0da80eb2e565d7348f8a796a3e00802e2c85bd80",
          "sha1": "f07d410e56ad9aabac55cae6cecf66bb9f9b0ef5",
          "md5": "bb097ff8b5274cd949ea84077b302be8"
        }
      ]
    }
  ]
}
