{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.6.0/micro-mock-test-helper-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-watchosx64-0.6.0.klib",
          "size": 9273,
          "sha512": "a390952c10b95a08e7ada201e58402550f3d55ba3306d75bd29dab6c8ea2a345a12a4b62f8df185b5203dd1f3ea3375d82d5d75aaed906aa56d6b698f03b9b35",
          "sha256": "5d0683c7643f4a5408f857bdda144710aa0c4eaf68fe96b1b9c6e06b1d695b0c",
          "sha1": "6f88c7404bfc26419b87696fb7e0a4c29f14ec88",
          "md5": "3bd3087974b6cb72f0c3418b22c05bb0"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-watchosx64-0.6.0-metadata.jar",
          "url": "micro-mock-test-helper-watchosx64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "916a9fc686a16cbf3fab5b383c9422653a8eb1f93ea56846c961f19976aca4091aa10ed468cac2e303fe3eb01ef843098e2de61a61c0ae1ff5866fd1a220e551",
          "sha256": "dfb7eccf93052dfda0fc3f749a3c83d42fd86d717cb163d63e8e396a8954ee90",
          "sha1": "8869c495a593a1bf3038341d69242aac458bf1e5",
          "md5": "21b95490ca98c877dbd2c39589fc25ac"
        }
      ]
    }
  ]
}
