{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.7.0/micro-mock-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-tvosarm64-0.7.0.klib",
          "size": 51609,
          "sha512": "aa59c8bf3fd5fd7574fad5b24eeca6c6aa70de4d0b1360200a28aa979697bb5617533726c9c17bc69865e97395e0c244bf77f66f83a3938e6497a0fabd1aef3a",
          "sha256": "4d862c04548c32264f8a6a35918aeccb80e9cf6309807c9549be16f0d40e039d",
          "sha1": "379e14831bb305343a8be96f800595425a4374e4",
          "md5": "cf66bb4d0f2e69290f79d36353f0cbc7"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-tvosarm64-0.7.0-metadata.jar",
          "url": "micro-mock-tvosarm64-0.7.0-metadata.jar",
          "size": 4713,
          "sha512": "bc091c102ce5d47bf7301d3f8692547bf4d33fb42721d404477826b9530965932064a556acf91c5a07e8b58342f72e98b6bc182df99e6dac6a560bd3c0b795dc",
          "sha256": "5962d957b4a3373161732a1bf92854490236e3bf268e121990cdb1a022efcf94",
          "sha1": "6b5ba3f9fd1ed15a8cc9b3235ee59ed8e1f71215",
          "md5": "3bba2c46d73c24f5855c8b12a076b90d"
        }
      ]
    }
  ]
}
