{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.7.0/micro-mock-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-tvosx64-0.7.0.klib",
          "size": 51593,
          "sha512": "141834870329fac07c54e4d446f91a7c60a274c32784de384d7efe5dff09138d7bd32ad78abc86c2903cc84686803d8f0395154d6c8adca6e31552a3a45b0b78",
          "sha256": "aabf27f442f10daad7d33650bb1f1590e9d0298ed5b212fd0230b1296e52134d",
          "sha1": "5e8e1c05844cfeaf5fe1ed79c57fe43926c51aec",
          "md5": "a588a8cf8967b15328655aa63b171e9b"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-tvosx64-0.7.0-metadata.jar",
          "url": "micro-mock-tvosx64-0.7.0-metadata.jar",
          "size": 4713,
          "sha512": "82bd84c671f88947a75b557994dc240aea4ed4cfb2ec1d1df50c583e927d35145c4f188c42ff9163fb838ddb61e1c6a2c92c789c1f8222170a56e630a55495c9",
          "sha256": "ed12150d894bae7ffeefd282a0ac18ee2a6539345a2d77cab804fa1d564d4fb8",
          "sha1": "4846b66a8bee460befc80cb5d8cf305ab4f26b13",
          "md5": "ed9fe431518d5b0cf9953c437c01ad6f"
        }
      ]
    }
  ]
}
