= MocKMP Setup

== Standard test setup

First, add the gradle plugins:

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
plugins {
    kotlin("multiplatform") version "{kotlin-version}"
    id("com.google.devtools.ksp") version "{ksp-version}"
    id("org.kodein.mock.mockmp") version "{version}"
}
----

IMPORTANT: MocKMP uses KSP but does not install it in your project.
This is because the KSP version to use depends on the version of Kotlin you are using.
It is therefore your responsibility to install it on your project along with MocKMP.

Then, configure your Kotlin targets and dependencies.
For example:

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
kotlin {
    androidTarget()
    jvmToolchain(17)

    iosArm64()
    iosSimulatorArm64()
    iosX64()

    sourceSets {
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        androidUnitTest.dependencies {
            implementation(kotlin("test-junit"))
        }
    }
}
----

Finally, apply MocKMP to your test source sets:

IMPORTANT: This must be done *after* configuring Kotlin targets.

[[mockmp-gradle-config]]
[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
mockmp {
    onTest()
    // OR
    onTest {
        withHelper()
    }
}
----

[[junit-version]]
[TIP]
====
The `withHelper()` *is optional* and will add the `TestsWithMocks` helper class dependency to your project.
It will by default try to detect which JUnit version your JVM / Android target is using and may fail. +
You can force the JUnit version by using `withHelper(junit4)` or `withHelper(junit5)`:

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
mockmp {
    onTest {
        withHelper(junit5)
    }
}
----
====

== Applying to main source sets

In some cases, you may need to apply the processor to the common-main source-set instead of common-test.

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
mockmp {
    onMain {
        public()
    }
}
----

IMPORTANT: The `withHelper()` JUnit detection *will fail* when applying MocKMP to main source-sets.
If you want to add the `TestsWithMocks` helper class to your main source-sets, you must specify explicitely which JUnit version to use.


== Other configurations

[source,kotlin,subs="verbatim,attributes"]
.build.gradle.kts
----
mockmp {
    onTest { // or onMain

        // By default, MocKMP will be applied to all targets.
        // This is therefore not necessary (as it is the default).
        allTargets()
        // But you can instead apply it to only a subset of specific targets.
        specificTargets("jvm", "iosSimulatorArm64")

        // If you want the generated mocks & fakes to be public instead of internal.
        public()
        // or
        public(true)

        // By default, the mocks & fakes accessors will be generated in the
        // org.kodein.mock.generated package.
        // You may change this if you have multiple modules using MocKMP, to avoid
        // collision between generated accessors.
        accessorsPackage("com.myproject.mockmp.generated")

    }
}
----
