{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.7.0/micro-mock-test-helper-0.7.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-watchosarm64-0.7.0.klib",
          "size": 9289,
          "sha512": "708a1e3c9f604974176334d73a13de8b9f9d49bd9b206afc97741c8f68b793aecfd458a642b6e530640d27fdb9e597823c1b6e75cf94e1040e9fe73db725a2d4",
          "sha256": "b7d187154bffc71a6a71105788e7d8914d6e5e5d4a656f86c95c8a10a9f22d1f",
          "sha1": "64797918d795801c5d902c84626c8ddec5ae4b72",
          "md5": "01a0dc928408bc843312ca0ac1704863"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-watchosarm64-0.7.0-metadata.jar",
          "url": "micro-mock-test-helper-watchosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "794880014297b7780d9e8b8a8945d9403d81b47a785c3f97bbd5686e064e1eded9b2a26856dd341670ac19ed0f911a4bc4018283d6dd9c37ddbb2bc4b3b7c07c",
          "sha256": "1569311d397644002a5f8bf35125d793e0fe893ce7c8ccc0c1ce4ca61423397e",
          "sha1": "5b8c3dfa5785a315ce43d686609be00013606564",
          "md5": "25156441db3a0ae509a9cf0d9a75cef0"
        }
      ]
    }
  ]
}
