{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.2.0/micro-mock-0.2.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jvm-0.2.0.jar",
          "url": "micro-mock-jvm-0.2.0.jar",
          "size": 57950,
          "sha512": "867d3de0454c6b3a05fe88d7c43baa4533719b563b95f2d60ba36b1bdb498f9e9987fbb1bfe821feee539d55d9ec6cf6b22aa9b763bcdfd46b34162d0ab2c316",
          "sha256": "2231d289357c40ac625ecaec4b2b6582639ea264f11750abbaf741eec7580b3c",
          "sha1": "22dfa05e5ba4ef664fc366eb3b686e71baf0f989",
          "md5": "de677094922065fc738a144c7d799234"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.2"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jvm-0.2.0.jar",
          "url": "micro-mock-jvm-0.2.0.jar",
          "size": 57950,
          "sha512": "867d3de0454c6b3a05fe88d7c43baa4533719b563b95f2d60ba36b1bdb498f9e9987fbb1bfe821feee539d55d9ec6cf6b22aa9b763bcdfd46b34162d0ab2c316",
          "sha256": "2231d289357c40ac625ecaec4b2b6582639ea264f11750abbaf741eec7580b3c",
          "sha1": "22dfa05e5ba4ef664fc366eb3b686e71baf0f989",
          "md5": "de677094922065fc738a144c7d799234"
        }
      ]
    }
  ]
}
