{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.2.0/micro-mock-0.2.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jvm-0.2.0.jar",
          "url": "micro-mock-jvm-0.2.0.jar",
          "size": 57950,
          "sha512": "8ee8b530640ead2ade43ec09239792407fe4b14ebe0ba7e4427bca2b0c763cd78a06935993bad719dcfbb47175db222c5ad7db0419cd313a964c50b75ecad24e",
          "sha256": "341fcd37c823587b7bb53fdbbd9d9973741eb57bc5b352f0836597ae1c2e9477",
          "sha1": "1b287c4d7b89ec11dcf874ef9d35e32898f469c3",
          "md5": "5efd9141a5eff3ef702cc591b4231f2d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.2"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-jvm-0.2.0.jar",
          "url": "micro-mock-jvm-0.2.0.jar",
          "size": 57950,
          "sha512": "8ee8b530640ead2ade43ec09239792407fe4b14ebe0ba7e4427bca2b0c763cd78a06935993bad719dcfbb47175db222c5ad7db0419cd313a964c50b75ecad24e",
          "sha256": "341fcd37c823587b7bb53fdbbd9d9973741eb57bc5b352f0836597ae1c2e9477",
          "sha1": "1b287c4d7b89ec11dcf874ef9d35e32898f469c3",
          "md5": "5efd9141a5eff3ef702cc591b4231f2d"
        }
      ]
    }
  ]
}
