{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock-test-helper/0.6.0/micro-mock-test-helper-0.6.0.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock-test-helper",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper.klib",
          "url": "micro-mock-test-helper-watchosarm64-0.6.0.klib",
          "size": 9289,
          "sha512": "708a1e3c9f604974176334d73a13de8b9f9d49bd9b206afc97741c8f68b793aecfd458a642b6e530640d27fdb9e597823c1b6e75cf94e1040e9fe73db725a2d4",
          "sha256": "b7d187154bffc71a6a71105788e7d8914d6e5e5d4a656f86c95c8a10a9f22d1f",
          "sha1": "64797918d795801c5d902c84626c8ddec5ae4b72",
          "md5": "01a0dc928408bc843312ca0ac1704863"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.kodein.micromock",
          "module": "micro-mock",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-test-helper-watchosarm64-0.6.0-metadata.jar",
          "url": "micro-mock-test-helper-watchosarm64-0.6.0-metadata.jar",
          "size": 261,
          "sha512": "916a9fc686a16cbf3fab5b383c9422653a8eb1f93ea56846c961f19976aca4091aa10ed468cac2e303fe3eb01ef843098e2de61a61c0ae1ff5866fd1a220e551",
          "sha256": "dfb7eccf93052dfda0fc3f749a3c83d42fd86d717cb163d63e8e396a8954ee90",
          "sha1": "8869c495a593a1bf3038341d69242aac458bf1e5",
          "md5": "21b95490ca98c877dbd2c39589fc25ac"
        }
      ]
    }
  ]
}
