{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.micromock",
    "module": "micro-mock-gradle-plugin",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "micro-mock-gradle-plugin-0.2.0.jar",
          "url": "micro-mock-gradle-plugin-0.2.0.jar",
          "size": 11702,
          "sha512": "5c4e26cac7e59733c0395b5a82323b8fbd8613c47eb7febefd497be0f7fd9bb9447f1b64c4b3c677dc45c2e7709a31946368927f98d706471ddbd0c0eb1e8860",
          "sha256": "cd40e9cd0a06357d173cd8a87cc14e6c68d1a6a423e51e5a4853a1ad1edd2cb8",
          "sha1": "9783796eecd7a617538bb7bd64a377117de98d30",
          "md5": "a1251538b0932891cb91093e537491cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.5.31-1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-gradle-plugin-0.2.0.jar",
          "url": "micro-mock-gradle-plugin-0.2.0.jar",
          "size": 11702,
          "sha512": "5c4e26cac7e59733c0395b5a82323b8fbd8613c47eb7febefd497be0f7fd9bb9447f1b64c4b3c677dc45c2e7709a31946368927f98d706471ddbd0c0eb1e8860",
          "sha256": "cd40e9cd0a06357d173cd8a87cc14e6c68d1a6a423e51e5a4853a1ad1edd2cb8",
          "sha1": "9783796eecd7a617538bb7bd64a377117de98d30",
          "md5": "a1251538b0932891cb91093e537491cd"
        }
      ]
    }
  ]
}
