{
  "formatVersion": "1.1",
  "component": {
    "url": "../../micro-mock/0.4.1/micro-mock-0.4.1.module",
    "group": "org.kodein.micromock",
    "module": "micro-mock",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock.klib",
          "url": "micro-mock-tvosx64-0.4.1.klib",
          "size": 33683,
          "sha512": "c509f4593cd695ce468eae6175b00931ef67a4555672a4c9fc47f78d02e6ff91265c491d1ff78e6384c897a1e03fc34cd115fae929f747dedbbd3aaabeaf8478",
          "sha256": "d39f6bddb17b69a778cf0e5157f29a9b390bc1e2d810afb9afd24851b01e6013",
          "sha1": "3e517f55762dd8dd9caa3c03ec57b02ad2c31687",
          "md5": "acd1d404b634ba972b8f95809c84e2b9"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "micro-mock-tvosx64-0.4.1-metadata.jar",
          "url": "micro-mock-tvosx64-0.4.1-metadata.jar",
          "size": 4310,
          "sha512": "a62b4fe6cd1060e853cfad63bc4b37da9479ffacbde2f74bcc89d023f76f980398842afd881d385f74386210bc774fab3548428ef4bc4390803dab48badec411",
          "sha256": "8f568fe9588da48bce3eeb861efb0c3944673e9594ecfec6c529da128e3efba0",
          "sha1": "ac7da078e9dc675da81c2a5b57dca8b92fab77b0",
          "md5": "1381bfc2448442be2d2d7d859cb66813"
        }
      ]
    }
  ]
}
